(function(g){var window=this;var Eja=function(a,b){return g.cc(a,b)},Fja=function(a){if(a.jc&&"function"==typeof a.jc)return a.jc();
if(g.w(a))return a.split("");if(g.Aa(a)){for(var b=[],c=a.length,d=0;d<c;d++)b.push(a[d]);return b}return g.Zb(a)},Gja=function(a,b){if(a.forEach&&"function"==typeof a.forEach)a.forEach(b,void 0);
else if(g.Aa(a)||g.w(a))(0,g.D)(a,b,void 0);else{if(a.qd&&"function"==typeof a.qd)var c=a.qd();else if(a.jc&&"function"==typeof a.jc)c=void 0;else if(g.Aa(a)||g.w(a)){c=[];for(var d=a.length,e=0;e<d;e++)c.push(e)}else c=g.$b(a);d=Fja(a);e=d.length;for(var f=0;f<e;f++)b.call(void 0,d[f],c&&c[f],a)}},k4=function(a){g.np(a,"zx",g.Ib());
return a},l4=function(a,b,c){g.za(c)||(c=[String(c)]);
g.tp(a.o,b,c)},m4=function(){},n4=function(a){if(!a.l&&"undefined"==typeof window.XMLHttpRequest&&"undefined"!=typeof window.ActiveXObject){for(var b=["MSXML2.XMLHTTP.6.0",
"MSXML2.XMLHTTP.3.0","MSXML2.XMLHTTP","Microsoft.XMLHTTP"],c=0;c<b.length;c++){var d=b[c];try{return new window.ActiveXObject(d),a.l=d}catch(e){}}throw Error("Could not create ActiveXObject. ActiveX might be disabled, or MSXML might not be installed");}return a.l},o4=function(a){var b;
(b=a.g)||(b={},n4(a)&&(b[0]=!0,b[1]=!0),b=a.g=b);return b},p4=function(a){return(a=n4(a))?new window.ActiveXObject(a):new window.XMLHttpRequest},q4=function(a,b){return b+" ["+a.ba+" "+a.I+" "+a.getStatus()+"]"},Hja=function(a){return"content-type"==a.toLowerCase()},r4=function(a){a.g&&a.L&&(a.g.ontimeout=null);
a.F&&(g.x.clearTimeout(a.F),a.F=null)},Ija=function(a){return g.Gd&&g.zc(9)&&g.va(a.timeout)&&g.t(a.ontimeout)},s4=function(a){a.V||(a.V=!0,a.dispatchEvent("complete"),a.dispatchEvent("error"))},t4=function(a,b){if(a.g){r4(a);
var c=a.g,d=a.P[0]?g.wa:null;a.g=null;a.P=null;b||a.dispatchEvent("ready");try{c.onreadystatechange=d}catch(e){}}},u4=function(a,b){a.l=!1;
a.g&&(a.o=!0,a.g.abort(),a.o=!1);a.B=b;a.A=5;s4(a);t4(a)},v4=function(a){return a.g?a.g.readyState:0},w4=function(a){if(a.l&&"undefined"!=typeof g.xW)if(a.P[1]&&4==v4(a)&&2==a.getStatus())q4(a,"Local request error detected and ignored");
else if(a.G&&4==v4(a))g.zg(a.gs,0,a);else if(a.dispatchEvent("readystatechange"),4==v4(a)){q4(a,"Request complete");a.l=!1;try{var b=a.getStatus();a:switch(b){case 200:case 201:case 202:case 204:case 206:case 304:case 1223:var c=!0;break a;default:c=!1}var d;if(!(d=c)){var e;if(e=0===b){var f=g.Sg(String(a.I))[1]||null;if(!f&&g.x.self&&g.x.self.location){var k=g.x.self.location.protocol;f=k.substr(0,k.length-1)}e=!Jja.test(f?f.toLowerCase():"")}d=e}if(d)a.dispatchEvent("complete"),a.dispatchEvent("success");
else{a.A=6;try{var l=2<v4(a)?a.g.statusText:""}catch(m){l=""}a.B=l+" ["+a.getStatus()+"]";s4(a)}}finally{t4(a)}}},x4=function(a){g.Df.call(this);
this.headers=new g.ap;this.R=a||null;this.l=!1;this.P=this.g=null;this.ba=this.I="";this.A=0;this.B="";this.o=this.W=this.G=this.V=!1;this.C=0;this.F=null;this.da="";this.L=this.X=!1},y4=function(a){try{return a.g?a.g.responseText:""}catch(b){return""}},Kja=function(a,b){var c=[];
g.Dl(b,function(a){try{var b=g.sr.prototype.l.call(this,a,!0)}catch(f){if("Storage: Invalid value was encountered"==f)return;throw f;}g.t(b)?g.rr(b)&&c.push(a):c.push(a)},a);
return c},Lja=function(a,b){var c=Kja(a,b);
(0,g.D)(c,function(a){g.sr.prototype.remove.call(this,a)},a)},Mja=function(a,b,c,d){var e=new g.dp(null,void 0);
a&&g.ep(e,a);b&&g.fp(e,b);c&&g.gp(e,c);d&&(e.l=d);return e},z4=function(){this.g=[];
this.l=[]},A4=function(a){g.Cu[a]&&(a=g.Cu[a],(0,g.D)(a,function(a){g.Au[a]&&delete g.Au[a]}),a.length=0)},Nja=function(a){var b=g.zu();
if(b)if(b.clear(a),a)A4(a);else for(var c in g.Cu)A4(c)},B4=function(a){this.app=this.name=this.id="";
this.type="REMOTE_CONTROL";this.obfuscatedGaiaId=this.avatar=this.username="";this.o=!1;this.capabilities=new window.Set;this.experiments=new window.Set;this.theme="u";new g.ap;this.g=this.l="";a&&(this.id=a.id||a.name,this.name=a.name,this.app=a.app,this.type=a.type||"REMOTE_CONTROL",this.username=a.user||"",this.avatar=a.userAvatarUri||"",this.obfuscatedGaiaId=a.obfuscatedGaiaId||"",this.theme=a.theme||"u",Oja(this,a.capabilities||""),Pja(this,a.experiments||""),this.l=a.remoteControllerUrl||"",
this.g=a.localChannelEncryptionKey||"")},Oja=function(a,b){a.capabilities.clear();
(0,g.Vd)(b.split(","),g.B(Eja,Qja)).forEach(function(b){a.capabilities.add(b)})},Pja=function(a,b){a.experiments.clear();
b.split(",").forEach(function(b){a.experiments.add(b)})},C4=function(a){a=a||{};
this.name=a.name||"";this.id=a.id||a.screenId||"";this.token=a.token||a.loungeToken||"";this.uuid=a.uuid||a.dialId||""},D4=function(a,b){return!!b&&(a.id==b||a.uuid==b)},E4=function(a){return{name:a.name,
screenId:a.id,loungeToken:a.token,dialId:a.uuid}},Rja=function(a){return new C4(a)},F4=function(a){return g.za(a)?(0,g.G)(a,Rja):[]},G4=function(a){return a?'{name:"'+a.name+'",id:'+a.id.substr(0,6)+"..,token:"+(a.token?".."+a.token.slice(-6):"-")+",uuid:"+(a.uuid?".."+a.uuid.slice(-6):"-")+"}":"null"},H4=function(a){return g.za(a)?"["+(0,g.G)(a,G4).join(",")+"]":"null"},I4=function(){return"xxxxxxxx-xxxx-4xxx-yxxx-xxxxxxxxxxxx".replace(/[xy]/g,function(a){var b=16*Math.random()|0;
return("x"==a?b:b&3|8).toString(16)})},Sja=function(a){return(0,g.G)(a,function(a){return{key:a.id,
name:a.name}})},J4=function(a,b){return g.Oa(a,function(a){return a||b?!a!=!b?!1:a.id==b.id:!0})},K4=function(a,b){return g.Oa(a,function(a){return D4(a,b)})},Tja=function(){var a=(0,g.Cv)();
a&&Lja(a,a.g.Pe(!0))},L4=function(){var a=g.Fv("yt-remote-connected-devices")||[];
g.ib(a);return a},Uja=function(a){if(0==a.length)return[];
var b=a[0].indexOf("#"),c=-1==b?a[0]:a[0].substring(0,b);return(0,g.G)(a,function(a,b){return 0==b?a:a.substring(c.length)})},M4=function(a){g.Ev("yt-remote-connected-devices",a,86400)},O4=function(){if(N4)return N4;
var a=g.Fv("yt-remote-device-id");a||(a=I4(),g.Ev("yt-remote-device-id",a,31536E3));for(var b=L4(),c=1,d=a;g.Sa(b,d);)c++,d=a+"#"+c;return N4=d},P4=function(){var a=L4(),b=O4();
g.Sa(a,b);g.Hv()&&g.nb(a,b);a=Uja(a);if(0==a.length)try{g.nv("remote_sid")}catch(c){}else try{g.mv("remote_sid",a.join(","),-1)}catch(c){}},Q4=function(){return g.Fv("yt-remote-session-browser-channel")},R4=function(){return g.Fv("yt-remote-local-screens")||[]},S4=function(){g.Ev("yt-remote-lounge-token-expiration",!0,86400)},Vja=function(a){5<a.length&&(a=a.slice(a.length-5));
var b=(0,g.G)(R4(),function(a){return a.loungeToken}),c=(0,g.G)(a,function(a){return a.loungeToken});
(0,g.Ho)(c,function(a){return!g.Sa(b,a)})&&S4();
g.Ev("yt-remote-local-screens",a,31536E3)},Wja=function(a,b){g.Ev("yt-remote-session-browser-channel",a);
g.Ev("yt-remote-session-screen-id",b);var c=L4(),d=O4();g.Sa(c,d)||c.push(d);M4(c);P4()},T4=function(a){a||(g.Gv("yt-remote-session-screen-id"),g.Gv("yt-remote-session-video-id"));
P4();a=L4();g.Xa(a,O4());M4(a)},V4=function(){if(!U4){var a=g.Er();
a&&(U4=new g.mr(a))}return U4?!!U4.get("yt-remote-use-staging-server"):!1},Xja=function(){var a=window.document.createElement("a");
g.hd(a,"https://www.gstatic.com/cv/js/sender/v1/cast_sender.js");a=a.href.replace(/^[a-zA-Z]+:\/\//,"//");return"js-"+g.Mb(a)},Yja=function(a,b){var c=g.Od("SCRIPT");
c.id=a;c.onload=function(){b&&(0,window.setTimeout)(b,0)};
c.onreadystatechange=function(){switch(c.readyState){case "loaded":case "complete":c.onload()}};
g.id(c,g.me("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js"));var d=window.document.getElementsByTagName("head")[0]||window.document.body;d.insertBefore(c,d.firstChild);return c},Zja=function(){var a=Xja(),b=window.document.getElementById(a),c=b&&g.Jt(b,"loaded");
c||b&&!c||(b=Yja(a,function(){g.Jt(b,"loaded")||(g.It(b,"loaded","true"),g.Gu(a),g.ws(g.B(Nja,a),0))}))},W4=function(a){return!!window.document.currentScript&&(-1!=window.document.currentScript.src.indexOf("?"+a)||-1!=window.document.currentScript.src.indexOf("&"+a))},X4=function(){return"function"==typeof window.__onGCastApiAvailable?window.__onGCastApiAvailable:null},Z4=function(a){a.length?Y4(a.shift(),function(){Z4(a)}):$4()},$ja=function(a){return"chrome-extension://"+a+a5},Y4=function(a,b,c){var d=
window.document.createElement("script");
d.onerror=b;c&&(d.onload=c);d.src=a;(window.document.head||window.document.documentElement).appendChild(d)},b5=function(a){return 0<=window.navigator.userAgent.indexOf(a)},$4=function(){var a=X4();
a&&a(!1,"No cast extension found")},c5=function(){if(aka){var a=2,b=X4(),c=function(){a--;
0==a&&b&&b(!0)};
window.__onGCastApiAvailable=c;Y4("//www.gstatic.com/cast/sdk/libs/sender/1.0/cast_framework.js",$4,c)}},bka=function(){var a=window.__gCrWeb&&window.__gCrWeb.message&&window.__gCrWeb.message.invokeOnHost;
a&&(c5(),a({command:"cast.sender.init"}))},cka=function(){c5();
var a=window.navigator.userAgent.match(/Chrome\/([0-9]+)/);Z4(["//www.gstatic.com/eureka/clank/"+(a?(0,window.parseInt)(a[1],10):0)+a5,"//www.gstatic.com/eureka/clank"+a5])},d5=function(a,b,c){g.I.call(this);
this.C=null!=c?(0,g.A)(a,c):a;this.Ac=b;this.B=(0,g.A)(this.eA,this);this.g=!1;this.l=0;this.o=this.Aa=null;this.A=[]},e5=function(){},f5=function(a,b,c,d){this.g=a;
this.o=b;this.F=c;this.C=d||1;this.A=45E3;this.ca=new g.up(this);this.l=new g.yg;this.l.setInterval(250)},h5=function(a,b,c){a.qh=1;
a.Hf=k4(b.clone());a.Ng=c;a.B=!0;g5(a,null)},i5=function(a,b,c,d,e){a.qh=1;
a.Hf=k4(b.clone());a.Ng=null;a.B=c;e&&(a.Dw=!1);g5(a,d)},g5=function(a,b){a.Jh=(0,g.E)();
j5(a);a.Zf=a.Hf.clone();l4(a.Zf,"t",a.C);a.rj=0;a.hc=a.g.Fm(a.g.lj()?b:null);0<a.an&&(a.vl=new g.sm((0,g.A)(a.Rx,a,a.hc),a.an));a.ca.fa(a.hc,"readystatechange",a.EJ);var c=a.xg?g.jc(a.xg):{};a.Ng?(a.Sl="POST",c["Content-Type"]="application/x-www-form-urlencoded",a.hc.send(a.Zf,a.Sl,a.Ng,c)):(a.Sl="GET",a.Dw&&!g.Id&&(c.Connection="close"),a.hc.send(a.Zf,a.Sl,null,c));a.g.de(1)},q5=function(a,b,c){for(var d=!0;!a.pg&&a.rj<c.length;){var e=dka(a,c);
if(e==k5){4==b&&(a.If=4,l5(15),d=!1);break}else if(e==m5){a.If=4;l5(16);d=!1;break}else n5(a,e)}4==b&&0==c.length&&(a.If=1,l5(17),d=!1);a.fe=a.fe&&d;d||(o5(a),p5(a))},dka=function(a,b){var c=a.rj,d=b.indexOf("\n",c);
if(-1==d)return k5;c=Number(b.substring(c,d));if((0,window.isNaN)(c))return m5;d+=1;if(d+c>b.length)return k5;var e=b.substr(d,c);a.rj=d+c;return e},t5=function(a,b){a.Jh=(0,g.E)();
j5(a);var c=b?window.location.hostname:"";a.Zf=a.Hf.clone();g.np(a.Zf,"DOMAIN",c);g.np(a.Zf,"t",a.C);try{a.ge=new window.ActiveXObject("htmlfile")}catch(n){o5(a);a.If=7;l5(22);p5(a);return}var d="<html><body>";if(b){for(var e="",f=0;f<c.length;f++){var k=c.charAt(f);if("<"==k)e+="\\x3c";else if(">"==k)e+="\\x3e";else{var l=k;if(l in r5)k=r5[l];else if(l in s5)k=r5[l]=s5[l];else{var m=l.charCodeAt(0);if(31<m&&127>m)k=l;else{if(256>m){if(k="\\x",16>m||256<m)k+="0"}else k="\\u",4096>m&&(k+="0");k+=m.toString(16).toUpperCase()}k=
r5[l]=k}e+=k}}d+='<script>document.domain="'+e+'"\x3c/script>'}d+="</body></html>";c=g.jd(g.Fc("b/12014412"),d);a.ge.open();a.ge.write(g.bd(c));a.ge.close();a.ge.parentWindow.m=(0,g.A)(a.VI,a);a.ge.parentWindow.d=(0,g.A)(a.Ov,a,!0);a.ge.parentWindow.rpcClose=(0,g.A)(a.Ov,a,!1);c=a.ge.createElement("DIV");a.ge.parentWindow.document.body.appendChild(c);d=g.Pc(a.Zf.toString());d=g.Cb(g.Mc(d));d=g.jd(g.Fc("b/12014412"),'<iframe src="'+d+'"></iframe>');c.innerHTML=g.bd(d);a.g.de(1)},j5=function(a){a.Sp=
(0,g.E)()+a.A;
u5(a,a.A)},u5=function(a,b){if(null!=a.Vh)throw Error("WatchDog timer not null");
a.Vh=v5((0,g.A)(a.iJ,a),b)},w5=function(a){a.Vh&&(g.x.clearTimeout(a.Vh),a.Vh=null)},p5=function(a){a.g.ds()||a.pg||a.g.kl(a)},o5=function(a){w5(a);
g.Ye(a.vl);a.vl=null;a.l.stop();g.wp(a.ca);if(a.hc){var b=a.hc;a.hc=null;b.abort();b.dispose()}a.ge&&(a.ge=null)},n5=function(a,b){try{a.g.Iv(a,b),a.g.de(4)}catch(c){}},y5=function(a,b,c,d,e){if(0==d)c(!1);
else{var f=e||0;d--;x5(a,b,function(e){e?c(!0):g.x.setTimeout(function(){y5(a,b,c,d,f)},f)})}},x5=function(a,b,c){var d=new window.Image;
d.onload=function(){try{z5(d),c(!0)}catch(e){}};
d.onerror=function(){try{z5(d),c(!1)}catch(e){}};
d.onabort=function(){try{z5(d),c(!1)}catch(e){}};
d.ontimeout=function(){try{z5(d),c(!1)}catch(e){}};
g.x.setTimeout(function(){if(d.ontimeout)d.ontimeout()},b);
d.src=a},z5=function(a){a.onload=null;
a.onerror=null;a.onabort=null;a.ontimeout=null},A5=function(a){this.g=a;
this.l=new e5},C5=function(a){var b=B5(a.g,a.ci,"/mail/images/cleardot.gif");
k4(b);y5(b.toString(),5E3,(0,g.A)(a.Dz,a),3,2E3);a.de(1)},E5=function(a){var b=a.g.I;
if(null!=b)l5(5),b?(l5(11),D5(a.g,a,!1)):(l5(12),D5(a.g,a,!0));else if(a.Ad=new f5(a,void 0,void 0,void 0),a.Ad.xg=a.Xm,b=a.g,b=B5(b,b.lj()?a.zi:null,a.Zm),l5(5),!g.Gd||g.Bc(10))l4(b,"TYPE","xmlhttp"),i5(a.Ad,b,!1,a.zi,!1);else{l4(b,"TYPE","html");var c=a.Ad;a=!!a.zi;c.qh=3;c.Hf=k4(b.clone());t5(c,a)}},F5=function(a,b,c){this.g=1;
this.l=[];this.A=[];this.B=new e5;this.G=a||null;this.I=null!=b?b:null;this.C=c||!1},eka=function(a,b){this.g=a;
this.map=b;this.context=null},G5=function(a){g.$e.call(this,"statevent",a)},H5=function(a,b){g.$e.call(this,"timingevent",a);
this.size=b},I5=function(a){g.$e.call(this,"serverreachability",a)},M5=function(a){J5(a);
if(3==a.g){var b=a.Zi++,c=a.jk.clone();g.np(c,"SID",a.o);g.np(c,"RID",b);g.np(c,"TYPE","terminate");K5(a,c);b=new f5(a,a.o,b,void 0);b.qh=2;b.Hf=k4(c.clone());(new window.Image).src=b.Hf;b.Jh=(0,g.E)();j5(b)}L5(a)},O5=function(a){a.Oz(1,0);
a.jk=B5(a,null,a.Wm);N5(a)},J5=function(a){a.Af&&(a.Af.abort(),a.Af=null);
a.Kb&&(a.Kb.cancel(),a.Kb=null);a.Re&&(g.x.clearTimeout(a.Re),a.Re=null);P5(a);a.gd&&(a.gd.cancel(),a.gd=null);a.Df&&(g.x.clearTimeout(a.Df),a.Df=null)},Q5=function(a,b){if(0==a.g)throw Error("Invalid operation: sending map when state is closed");
a.l.push(new eka(a.oF++,b));2!=a.g&&3!=a.g||N5(a)},N5=function(a){a.gd||a.Df||(a.Df=v5((0,g.A)(a.Mv,a),0),a.lh=0)},T5=function(a,b){if(1==a.g){if(!b){a.Zi=Math.floor(1E5*Math.random());
var c=a.Zi++,d=new f5(a,"",c,void 0);d.xg=null;var e=R5(a),f=a.jk.clone();g.np(f,"RID",c);g.np(f,"CVER","1");K5(a,f);h5(d,f,e);a.gd=d;a.g=2}}else 3==a.g&&(b?S5(a,b):0==a.l.length||a.gd||S5(a))},S5=function(a,b){if(b)if(6<a.qg){a.l=a.A.concat(a.l);
a.A.length=0;var c=a.Zi-1;var d=R5(a)}else c=b.F,d=b.Ng;else c=a.Zi++,d=R5(a);var e=a.jk.clone();g.np(e,"SID",a.o);g.np(e,"RID",c);g.np(e,"AID",a.wh);K5(a,e);c=new f5(a,a.o,c,a.lh+1);c.xg=null;c.setTimeout(1E4+Math.round(1E4*Math.random()));a.gd=c;h5(c,e,d)},K5=function(a,b){if(a.Ic){var c=a.Ic.Kr();
c&&g.Tb(c,function(a,c){g.np(b,c,a)})}},R5=function(a){var b=Math.min(a.l.length,1E3),c=["count="+b];
if(6<a.qg&&0<b){var d=a.l[0].g;c.push("ofs="+d)}else d=0;for(var e=0;e<b;e++){var f=a.l[e].g,k=a.l[e].map;f=6>=a.qg?e:f-d;try{g.Tb(k,function(a,b){c.push("req"+f+"_"+b+"="+(0,window.encodeURIComponent)(a))})}catch(l){c.push("req"+f+"_type="+(0,window.encodeURIComponent)("_badmap"))}}a.A=a.A.concat(a.l.splice(0,b));
return c.join("&")},U5=function(a){a.Kb||a.Re||(a.F=1,a.Re=v5((0,g.A)(a.Lv,a),0),a.eh=0)},W5=function(a){if(a.Kb||a.Re||3<=a.eh)return!1;
a.F++;a.Re=v5((0,g.A)(a.Lv,a),V5(a,a.eh));a.eh++;return!0},D5=function(a,b,c){a.Rl=c;
a.te=b.Xe;a.C||O5(a)},P5=function(a){null!=a.sg&&(g.x.clearTimeout(a.sg),a.sg=null)},V5=function(a,b){var c=5E3+Math.floor(1E4*Math.random());
a.isActive()||(c*=2);return c*b},Y5=function(a,b){if(2==b||9==b){var c=null;
a.Ic&&(c=null);var d=(0,g.A)(a.kK,a);c||(c=new g.dp("//www.google.com/images/cleardot.gif"),k4(c));x5(c.toString(),1E4,d)}else l5(2);X5(a,b)},X5=function(a,b){a.g=0;
a.Ic&&a.Ic.Oq(b);L5(a);J5(a)},L5=function(a){a.g=0;
a.te=-1;if(a.Ic)if(0==a.A.length&&0==a.l.length)a.Ic.ym();else{g.$a(a.A);var b=g.$a(a.l);a.A.length=0;a.l.length=0;a.Ic.ym(b)}},B5=function(a,b,c){var d=g.op(c);
if(""!=d.g)b&&g.fp(d,b+"."+d.g),g.gp(d,d.B);else{var e=window.location;d=Mja(e.protocol,b?b+"."+e.hostname:e.hostname,e.port,c)}a.ki&&g.Tb(a.ki,function(a,b){g.np(d,b,a)});
g.np(d,"VER",a.qg);K5(a,d);return d},v5=function(a,b){if(!g.Ba(a))throw Error("Fn must not be null and must be a function");
return g.x.setTimeout(function(){a()},b)},l5=function(a){Z5.dispatchEvent(new G5(Z5,a))},$5=function(){},fka=function(a,b){this.action=a;
this.params=b||{}},a6=function(a,b){g.I.call(this);
this.g=new g.N(this.NI,0,this);g.J(this,this.g);this.Ac=5E3;this.l=0;if(g.Ba(a))b&&(a=(0,g.A)(a,b));else if(a&&g.Ba(a.handleEvent))a=(0,g.A)(a.handleEvent,a);else throw Error("Invalid listener argument");this.o=a},b6=function(a,b,c){this.L=a;
this.C=b;this.o=new g.kr;this.l=new a6(this.JK,this);this.g=null;this.K=!1;this.B=null;this.I="";this.G=this.A=0;this.F=[];this.P=c||!1},gka=function(a){return{firstTestResults:[""],
secondTestResults:!a.g.Rl,sessionId:a.g.o,arrayId:a.g.wh}},c6=function(a,b){a.G=b||0;
a.l.stop();a.g&&(3==a.g.g&&T5(a.g),M5(a.g));a.G=0},d6=function(a){return!!a.g&&3==a.g.g},hka=function(a,b){(a.C.loungeIdToken=b)||a.l.stop()},e6=function(a){this.port=this.domain="";
this.g="/api/lounge";this.l=!0;a=a||window.document.location.href;var b=g.Vg(a)||"";b&&(this.port=":"+b);this.domain=g.Ug(a)||"";a=g.Rb;0<=a.search("MSIE")&&(a=a.match(/MSIE ([\d.]+)/)[1],0>g.Lb(a,"10.0")&&(this.l=!1))},f6=function(a,b){var c=a.g;
if(g.t(void 0)?0:a.l)c="https://"+a.domain+a.port+a.g;return g.dh(c+b,{})},g6=function(a,b,c,d,e){a={format:"JSON",
method:"POST",context:a,timeout:5E3,withCredentials:!1,ob:g.B(a.A,d,!0),onError:g.B(a.o,e),Yc:g.B(a.B,e)};c&&(a.gb=c,a.headers={"Content-Type":"application/x-www-form-urlencoded"});return g.Ns(b,a)},ika=function(){var a=h6;
i6();j6.push(a);k6(j6)},l6=function(a,b){i6();
var c=j6,d=jka(a,String(b));0==c.length?kka(d):(k6(c),(0,g.D)(c,function(a){a(d)}))},i6=function(){j6||(j6=g.z("yt.mdx.remote.debug.handlers_")||[],g.y("yt.mdx.remote.debug.handlers_",j6,void 0))},kka=function(a){var b=(m6+1)%50;
m6=b;n6[b]=a;o6||(o6=49==b)},k6=function(a){var b=n6;
if(b[0]){var c=m6,d=o6?c:-1;do{d=(d+1)%50;var e=b[d];(0,g.D)(a,function(a){a(e)})}while(d!=c);
n6=Array(50);m6=-1;o6=!1}},jka=function(a,b){var c=((0,g.E)()-lka)/1E3;
c.toFixed&&(c=c.toFixed(3));var d=[];d.push("[",c+"s","] ");d.push("[","yt.mdx.remote","] ");d.push(a+": "+b,"\n");return d.join("")},p6=function(a){g.P.call(this);
this.F=a;this.g=[]},q6=function(a,b){var c=a.get(b.uuid)||a.get(b.id);
if(c){var d=c.name;c.id=b.id||c.id;c.name=b.name;c.token=b.token;c.uuid=b.uuid||c.uuid;return c.name!=d}a.g.push(b);return!0},mka=function(a,b){var c=a.g.length!=b.length;
a.g=(0,g.Vd)(a.g,function(a){return!!J4(b,a)});
for(var d=0,e=b.length;d<e;d++)c=q6(a,b[d])||c;return c},nka=function(a,b){var c=a.g.length;
a.g=(0,g.Vd)(a.g,function(a){return!(a||b?!a!=!b?0:a.id==b.id:1)});
return a.g.length<c},r6=function(a,b,c,d){g.P.call(this);
this.C=a;this.B=b;this.o=c;this.A=d;this.l=0;this.g=null;this.Aa=window.NaN},t6=function(a){p6.call(this,"LocalScreenService");
this.o=a;this.l=window.NaN;s6(this);this.info("Initializing with "+H4(this.g))},u6=function(a){if(a.g.length){var b=(0,g.G)(a.g,function(a){return a.id}),c=f6(a.o,"/pairing/get_lounge_token_batch");
g6(a.o,c,{screen_ids:b.join(",")},(0,g.A)(a.pA,a),(0,g.A)(a.oA,a))}},s6=function(a){var b=F4(R4());
b=(0,g.Vd)(b,function(a){return!a.uuid});
return mka(a,b)},v6=function(a,b){Vja((0,g.G)(a.g,E4));
b&&S4()},x6=function(a,b){g.P.call(this);
this.C=b;var c=g.Fv("yt-remote-online-screen-ids")||"";c=c?c.split(","):[];for(var d={},e=this.C(),f=0,k=e.length;f<k;++f){var l=e[f].id;d[l]=g.Sa(c,l)}this.g=d;this.B=a;this.o=this.A=window.NaN;this.l=null;w6("Initialized with "+g.Kg(this.g))},y6=function(a,b,c){var d=f6(a.B,"/pairing/get_screen_availability");
g6(a.B,d,{lounge_token:b.token},(0,g.A)(function(a){a=a.screens||[];for(var d=0,e=a.length;d<e;++d)if(a[d].loungeToken==b.token){c("online"==a[d].status);return}c(!1)},a),(0,g.A)(function(){c(!1)},a))},z6=function(a,b){a:if(g.Yb(b)!=g.Yb(a.g))var c=!1;
else{c=g.$b(b);for(var d=0,e=c.length;d<e;++d)if(!a.g[c[d]]){c=!1;break a}c=!0}c||(w6("Updated online screens: "+g.Kg(a.g)),a.g=b,a.O("screenChange"));oka(a)},A6=function(a){(0,window.isNaN)(a.o)||g.ys(a.o);
a.o=g.ws((0,g.A)(a.gp,a),0<a.A&&a.A<(0,g.E)()?2E4:1E4)},w6=function(a){l6("OnlineScreenService",a)},B6=function(a){var b={};
(0,g.D)(a.C(),function(a){a.token?b[a.token]=a.id:this.Cb("Requesting availability of screen w/o lounge token.")});
return b},oka=function(a){a=g.$b(g.Vb(a.g,function(a){return a}));
g.ib(a);a.length?g.Ev("yt-remote-online-screen-ids",a.join(","),60):g.Gv("yt-remote-online-screen-ids")},C6=function(a){p6.call(this,"ScreenService");
this.C=a;this.l=this.o=null;this.A=[];this.B={};pka(this)},E6=function(a,b,c,d,e,f){a.info("getAutomaticScreenByIds "+c+" / "+b);
c||(c=a.B[b]);var k=a.td();if(k=(c?K4(k,c):null)||K4(k,b)){k.uuid=b;var l=D6(a,k);y6(a.l,l,function(a){e(a?l:null)})}else c?qka(a,c,(0,g.A)(function(a){var f=D6(this,new C4({name:d,
screenId:c,loungeToken:a,dialId:b||""}));y6(this.l,f,function(a){e(a?f:null)})},a),f):e(null)},F6=function(a,b){for(var c=0,d=a.g.length;c<d;++c)if(a.g[c].name==b)return a.g[c];
return null},qka=function(a,b,c,d){a.info("requestLoungeToken_ for "+b);
var e={gb:{screen_ids:b},method:"POST",context:a,ob:function(a,e){var f=e&&e.screens||[];f[0]&&f[0].screenId==b?c(f[0].loungeToken):d(Error("Missing lounge token in token response"))},
onError:function(){d(Error("Request screen lounge token failed"))}};
g.Ns(f6(a.C,"/pairing/get_lounge_token_batch"),e)},G6=function(a){a.g=a.o.td();
var b=a.B,c={},d;for(d in b)c[b[d]]=d;b=0;for(d=a.g.length;b<d;++b){var e=a.g[b];e.uuid=c[e.id]||""}a.info("Updated manual screens: "+H4(a.g))},pka=function(a){H6(a);
a.o=new t6(a.C);a.o.subscribe("screenChange",(0,g.A)(a.CA,a));G6(a);a.A=F4(g.Fv("yt-remote-automatic-screen-cache")||[]);H6(a);a.info("Initializing automatic screens: "+H4(a.A));a.l=new x6(a.C,(0,g.A)(a.td,a,!0));a.l.subscribe("screenChange",(0,g.A)(function(){this.O("onlineScreenChange")},a))},D6=function(a,b){var c=a.get(b.id);
c?(c.uuid=b.uuid,b=c):((c=K4(a.A,b.uuid))?(c.id=b.id,c.token=b.token,b=c):a.A.push(b),g.Ev("yt-remote-automatic-screen-cache",(0,g.G)(a.A,E4)));H6(a);a.B[b.uuid]=b.id;g.Ev("yt-remote-device-id-map",a.B,31536E3);return b},H6=function(a){a.B=g.Fv("yt-remote-device-id-map")||{}},I6=function(a,b,c){g.P.call(this);
this.P=c;this.I=a;this.l=b;this.o=null},J6=function(a,b){l6(a.P,b)},L6=function(a,b){I6.call(this,a,b,"CastSession");
this.g=null;this.A=0;this.C=(0,g.A)(this.PK,this);this.B=(0,g.A)(this.tJ,this);this.A=g.ws((0,g.A)(function(){K6(this,null)},this),12E4)},rka=function(a){a.info("sendYoutubeMessage_: getMdxSessionStatus "+g.Kg(void 0));
var b={type:"getMdxSessionStatus"};a.g?a.g.sendMessage("urn:x-cast:com.google.youtube.mdx",b,g.wa,(0,g.A)(function(){J6(this,"Failed to send message: getMdxSessionStatus.")},a)):J6(a,"Sending yt message without session: "+g.Kg(b))},K6=function(a,b){g.ys(a.A);
if(b){if(a.info("onConnectedScreenId_: Received screenId: "+b),!a.o||a.o.id!=b){var c=(0,g.A)(a.ll,a),d=(0,g.A)(a.yd,a);a.Tr(b,c,d,5)}}else a.yd(Error("Waiting for session status timed out."))},M6=function(a,b,c){I6.call(this,a,b,"DialSession");
this.A=this.G=null;this.K="";this.R=c;this.B=null;this.F=g.wa;this.C=window.NaN;this.L=(0,g.A)(this.SK,this);this.g=g.wa},N6=function(a){a.g=a.I.Yx(a.K,a.l.label,a.l.friendlyName,(0,g.A)(function(a){this.g=g.wa;
this.ll(a)},a),(0,g.A)(function(a){this.g=g.wa;
this.yd(a)},a))},O6=function(a){var b={};
b.pairingCode=a.K;b.theme=a.R;if(a.B){var c=a.B.currentTime||0;b.v=a.B.videoId;b.t=c}V4()&&(b.env_useStageMdx=1);return g.bh(b)},P6=function(a,b){I6.call(this,a,b,"ManualSession");
this.g=g.ws((0,g.A)(this.yh,this,null),150)},Q6=function(a,b,c,d){g.P.call(this);
this.l=a;this.F=b||"233637DE";this.C=c||"cl";this.G=d||!1;this.g=null;this.B=!1;this.o=[];this.A=(0,g.A)(this.bI,this)},R6=function(a,b){return b?g.Oa(a.o,function(a){return D4(b,a.label)},a):null},S6=function(a){l6("Controller",a)},h6=function(a){window.chrome&&window.chrome.cast&&window.chrome.cast.logMessage&&window.chrome.cast.logMessage(a)},T6=function(a){return a.B||!!a.o.length||!!a.g},U6=function(a,b,c){b!=a.g&&(g.Ye(a.g),(a.g=b)?(c?a.O("yt-remote-cast2-receiver-resumed",b.l):a.O("yt-remote-cast2-receiver-selected",
b.l),b.subscribe("sessionScreen",(0,g.A)(a.Kv,a,b)),b.o?a.O("yt-remote-cast2-session-change",b.o):c&&a.g.yh(null)):a.O("yt-remote-cast2-session-change",null))},V6=function(a){var b=a.l.Xx(),c=a.g&&a.g.l;
a=(0,g.G)(b,function(a){c&&D4(a,c.label)&&(c=null);var b=a.uuid?a.uuid:a.id,d=R6(this,a);d?(d.label=b,d.friendlyName=a.name):(d=new window.chrome.cast.Receiver(b,a.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM);return d},a);
c&&(c.receiverType!=window.chrome.cast.ReceiverType.CUSTOM&&(c=new window.chrome.cast.Receiver(c.label,c.friendlyName),c.receiverType=window.chrome.cast.ReceiverType.CUSTOM),a.push(c));return a},vka=function(a,b,c,d,e,f,k){ska()?tka(b,e,f,k)&&(X6(!0),window.chrome&&window.chrome.cast&&window.chrome.cast.isAvailable?Y6(a,c):(window.__onGCastApiAvailable=function(b,d){b?Y6(a,c):(Z6("Failed to load cast API: "+d),$6(!1),X6(!1),g.Gv("yt-remote-cast-available"),g.Gv("yt-remote-cast-receiver"),a7(),c(!1))},
d?window.spf?window.spf.script.load("https://www.gstatic.com/cv/js/sender/v1/cast_sender.js","",void 0):Zja():b5("CriOS")?bka():b5("Android")&&b5("Chrome/")&&window.navigator.presentation?cka():window.chrome&&window.navigator.presentation&&!b5("Edge")?(c5(),Z4(uka.map($ja))):$4())):W6("Cannot initialize because not running Chrome")},a7=function(){W6("dispose");
var a=b7();a&&a.dispose();g.y("yt.mdx.remote.cloudview.instance_",null,void 0);c7(!1);g.Eu(d7);d7.length=0},e7=function(){return!!g.Fv("yt-remote-cast-installed")},f7=function(){var a=g.Fv("yt-remote-cast-receiver");
return a?a.friendlyName:null},g7=function(){W6("clearCurrentReceiver");
g.Gv("yt-remote-cast-receiver")},h7=function(){return e7()?b7()?b7().getCastSession():(Z6("getCastSelector: Cast is not initialized."),null):(Z6("getCastSelector: Cast API is not installed!"),null)},j7=function(){e7()?b7()?i7()?(W6("Requesting cast selector."),b7().requestSession()):(W6("Wait for cast API to be ready to request the session."),d7.push(g.Du("yt-remote-cast2-api-ready",j7))):Z6("requestCastSelector: Cast is not initialized."):Z6("requestCastSelector: Cast API is not installed!")},k7=
function(a,b){i7()?b7().setConnectedScreenStatus(a,b):Z6("setConnectedScreenStatus called before ready.")},ska=function(){var a=0<=g.Rb.search(/ (CrMo|Chrome|CriOS)\//);
return g.Ty||a},wka=function(a,b){b7().init(a,b)},tka=function(a,b,c,d){var e=!1;
b7()||(a=new Q6(a,b,c,d),a.subscribe("yt-remote-cast2-availability-change",function(a){g.Ev("yt-remote-cast-available",a);g.Hu("yt-remote-cast2-availability-change",a)}),a.subscribe("yt-remote-cast2-receiver-selected",function(a){W6("onReceiverSelected: "+a.friendlyName);
g.Ev("yt-remote-cast-receiver",a);g.Hu("yt-remote-cast2-receiver-selected",a)}),a.subscribe("yt-remote-cast2-receiver-resumed",function(a){W6("onReceiverResumed: "+a.friendlyName);
g.Ev("yt-remote-cast-receiver",a)}),a.subscribe("yt-remote-cast2-session-change",function(a){W6("onSessionChange: "+G4(a));
a||g.Gv("yt-remote-cast-receiver");g.Hu("yt-remote-cast2-session-change",a)}),g.y("yt.mdx.remote.cloudview.instance_",a,void 0),e=!0);
W6("cloudview.createSingleton_: "+e);return e},b7=function(){return g.z("yt.mdx.remote.cloudview.instance_")},Y6=function(a,b){$6(!0);
X6(!1);wka(a,function(a){a?(c7(!0),g.Gu("yt-remote-cast2-api-ready")):(Z6("Failed to initialize cast API."),$6(!1),g.Gv("yt-remote-cast-available"),g.Gv("yt-remote-cast-receiver"),a7());b(a)})},W6=function(a){l6("cloudview",a)},Z6=function(a){l6("cloudview",a)},$6=function(a){W6("setCastInstalled_ "+a);
g.Ev("yt-remote-cast-installed",a)},i7=function(){return!!g.z("yt.mdx.remote.cloudview.apiReady_")},c7=function(a){W6("setApiReady_ "+a);
g.y("yt.mdx.remote.cloudview.apiReady_",a,void 0)},X6=function(a){g.y("yt.mdx.remote.cloudview.initializing_",a,void 0)},l7=function(a){this.index=-1;
this.videoId=this.listId="";this.volume=this.g=-1;this.muted=!1;this.audioTrackId=null;this.F=this.G=0;this.l=null;this.hasNext=this.ue=!1;this.K=this.I=this.o=this.B=0;this.A=window.NaN;this.C=!1;this.reset(a)},m7=function(a){a.audioTrackId=null;
a.l=null;a.g=-1;a.ue=!1;a.hasNext=!1;a.G=0;a.F=(0,g.E)();a.B=0;a.o=0;a.I=0;a.K=0;a.A=window.NaN;a.C=!1},n7=function(a){return 1==a.g?((0,g.E)()-a.F)/1E3:0},o7=function(a,b){a.G=b;
a.F=(0,g.E)()},p7=function(a){switch(a.g){case 1:case 1081:return((0,g.E)()-a.F)/1E3+a.G;
case -1E3:return 0}return a.G},q7=function(a,b,c){var d=a.videoId;
a.videoId=b;a.index=c;b!=d&&m7(a)},r7=function(a){var b={};
b.index=a.index;b.listId=a.listId;b.videoId=a.videoId;b.playerState=a.g;b.volume=a.volume;b.muted=a.muted;b.audioTrackId=a.audioTrackId;b.trackData=g.kc(a.l);b.hasPrevious=a.ue;b.hasNext=a.hasNext;b.playerTime=a.G;b.playerTimeAt=a.F;b.seekableStart=a.B;b.seekableEnd=a.o;b.duration=a.I;b.loadedTime=a.K;b.liveIngestionTime=a.A;return b},u7=function(a,b){g.P.call(this);
this.g=0;this.A=a;this.C=[];this.B=new z4;this.o=this.l=null;this.I=(0,g.A)(this.VF,this);this.F=(0,g.A)(this.cj,this);this.G=(0,g.A)(this.UF,this);this.K=(0,g.A)(this.iG,this);var c=0;a?(c=a.getProxyState(),3!=c&&(a.subscribe("proxyStateChange",this.Up,this),s7(this))):c=3;0!=c&&(b?this.Up(c):g.ws((0,g.A)(function(){this.Up(c)},this),0));
var d=h7();d&&t7(this,d);this.subscribe("yt-remote-cast2-session-change",this.K)},v7=function(a){return new l7(a.A.getPlayerContextData())},s7=function(a){(0,g.D)("nowAutoplaying autoplayDismissed remotePlayerChange remoteQueueChange autoplayModeChange autoplayUpNext previousNextChange".split(" "),function(a){this.C.push(this.A.subscribe(a,g.B(this.YH,a),this))},a)},w7=function(a){(0,g.D)(a.C,function(a){this.A.unsubscribeByKey(a)},a);
a.C.length=0},x7=function(a,b){var c=a.B;
50>c.g.length+c.l.length&&a.B.l.push(b)},z7=function(a,b,c){var d=v7(a);
o7(d,c);-1E3!=d.g&&(d.g=b);y7(a,d)},A7=function(a,b,c){a.A.sendMessage(b,c)},y7=function(a,b){w7(a);
a.A.setPlayerContextData(r7(b));s7(a)},t7=function(a,b){a.o&&(a.o.removeUpdateListener(a.I),a.o.removeMediaListener(a.F),a.cj(null));
a.o=b;a.o&&(l6("CP","Setting cast session: "+a.o.sessionId),a.o.addUpdateListener(a.I),a.o.addMediaListener(a.F),a.o.media.length&&a.cj(a.o.media[0]))},B7=function(a){var b=a.l.media,c=a.l.customData;
if(b&&c){var d=v7(a);b.contentId!=d.videoId&&l6("CP","Cast changing video to: "+b.contentId);d.videoId=b.contentId;d.g=c.playerState;o7(d,a.l.getEstimatedTime());y7(a,d)}else l6("CP","No cast media video. Ignoring state update.")},C7=function(a,b,c){return(0,g.A)(function(a){this.Cb("Failed to "+b+" with cast v2 channel. Error code: "+a.code);
a.code!=window.chrome.cast.ErrorCode.TIMEOUT&&(this.Cb("Retrying "+b+" using MDx browser channel."),A7(this,b,c))},a)},D7=function(a,b,c){g.P.call(this);
this.B=window.NaN;this.R=!1;this.K=this.I=this.L=this.P=window.NaN;this.V=[];this.A=this.F=this.o=this.Na=this.g=null;this.va=a;this.V.push(g.Zt(window,"beforeunload",(0,g.A)(this.iA,this)));this.l=[];this.Na=new l7;this.W=b.id;this.g=xka(this,c);this.g.subscribe("handlerOpened",this.ZF,this);this.g.subscribe("handlerClosed",this.WF,this);this.g.subscribe("handlerError",this.XF,this);this.g.subscribe("handlerMessage",this.YF,this);hka(this.g,b.token);this.subscribe("remoteQueueChange",function(){var a=
this.Na.videoId;g.Hv()&&g.Ev("yt-remote-session-video-id",a)},this)},E7=function(a){l6("conn",a)},xka=function(a,b){return new b6(f6(a.va,"/bc"),b)},F7=function(a,b){a.O("proxyStateChange",b)},yka=function(a){a.B=g.ws((0,g.A)(function(){E7("Connecting timeout");
this.C(1)},a),2E4)},G7=function(a){g.ys(a.B);
a.B=window.NaN},H7=function(a){g.ys(a.P);
a.P=window.NaN},zka=function(a){I7(a);
a.L=g.ws((0,g.A)(function(){J7(this,"getNowPlaying")},a),2E4)},I7=function(a){g.ys(a.L);
a.L=window.NaN},L7=function(a,b){b&&(G7(a),H7(a));
b==(d6(a.g)&&(0,window.isNaN)(a.B))?b&&(F7(a,1),J7(a,"getSubtitlesTrack")):b?(a.X()&&a.Na.reset(),F7(a,1),J7(a,"getNowPlaying"),K7(a)):a.C(1)},Aka=function(a,b){var c=b.params.videoId;
delete b.params.videoId;c==a.Na.videoId&&(g.fc(b.params)?a.Na.l=null:a.Na.l=b.params,a.O("remotePlayerChange"))},M7=function(a,b){var c=b.params.videoId||b.params.video_id,d=(0,window.parseInt)(b.params.currentIndex,10);
a.Na.listId=b.params.listId||a.Na.listId;q7(a.Na,c,d);a.O("remoteQueueChange")},Bka=function(a,b){b.params=b.params||{};
M7(a,b);N7(a,b);a.O("autoplayDismissed")},N7=function(a,b){var c=(0,window.parseInt)(b.params.currentTime||b.params.current_time,10);
o7(a.Na,(0,window.isNaN)(c)?0:c);c=(0,window.parseInt)(b.params.state,10);c=(0,window.isNaN)(c)?-1:c;-1==c&&-1E3==a.Na.g&&(c=-1E3);a.Na.g=c;c=Number(b.params.loadedTime);a.Na.K=(0,window.isNaN)(c)?0:c;c=Number(b.params.duration);a.Na.I=(0,window.isNaN)(c)?0:c;c=a.Na;var d=Number(b.params.liveIngestionTime);c.A=d;c.C=(0,window.isNaN)(d)?!1:!0;c=a.Na;d=Number(b.params.seekableStartTime);var e=Number(b.params.seekableEndTime);c.B=(0,window.isNaN)(d)?0:d;c.o=(0,window.isNaN)(e)?0:e;1==a.Na.g?zka(a):I7(a);
a.O("remotePlayerChange")},Cka=function(a,b){if(-1E3!=a.Na.g){var c=1085;
switch((0,window.parseInt)(b.params.adState,10)){case 1:c=1081;break;case 2:c=1084;break;case 0:c=1083}a.Na.g=c;c=(0,window.parseInt)(b.params.currentTime,10);o7(a.Na,(0,window.isNaN)(c)?0:c);a.O("remotePlayerChange")}},Dka=function(a,b){var c="true"==b.params.muted;
a.Na.volume=(0,window.parseInt)(b.params.volume,10);a.Na.muted=c;a.O("remotePlayerChange")},Eka=function(a,b){a.F=b.params.videoId;
a.O("nowAutoplaying",(0,window.parseInt)(b.params.timeout,10))},Fka=function(a,b){var c="true"==b.params.hasNext;
a.Na.ue="true"==b.params.hasPrevious;a.Na.hasNext=c;a.O("previousNextChange")},K7=function(a){g.ys(a.K);
a.K=g.ws((0,g.A)(a.C,a,1),864E5)},J7=function(a,b,c){c?E7("Sending: action="+b+", params="+g.Kg(c)):E7("Sending: action="+b);
a.g.sendMessage(b,c)},O7=function(a){p6.call(this,"ScreenServiceProxy");
this.zc=a;this.l=[];this.l.push(this.zc.$_s("screenChange",(0,g.A)(this.NK,this)));this.l.push(this.zc.$_s("onlineScreenChange",(0,g.A)(this.FH,this)))},Kka=function(a){var b={device:"Desktop",
app:"youtube-desktop"};b=g.os("MDX_CONFIG")||b;Tja();P4();P7||(P7=new e6(b?b.loungeApiHost:void 0),V4()&&(P7.g="/api/loungedev"));Q7||(Q7=g.z("yt.mdx.remote.deferredProxies_")||[],g.y("yt.mdx.remote.deferredProxies_",Q7,void 0));Gka();var c=R7();if(!c){var d=new C6(P7);g.y("yt.mdx.remote.screenService_",d,void 0);c=R7();var e=!1,f=void 0,k=void 0,l=!1;b&&(e=!!b.loadCastApiSetupScript,f=b.appId,k=b.theme,l=!!b.disableDial);vka(a,d,function(a){a?S7()&&k7(S7(),"YouTube TV"):d.subscribe("onlineScreenChange",
function(){g.Hu("yt-remote-receiver-availability-change")})},e,f,k,l)}b&&!g.z("yt.mdx.remote.initialized_")&&(g.y("yt.mdx.remote.initialized_",!0,void 0),T7("Initializing: "+g.Kg(b)),U7.push(g.Du("yt-remote-cast2-availability-change",function(){g.Hu("yt-remote-receiver-availability-change")})),U7.push(g.Du("yt-remote-cast2-receiver-selected",function(){V7(null);
g.Hu("yt-remote-auto-connect","cast-selector-receiver")})),U7.push(g.Du("yt-remote-cast2-receiver-resumed",function(){g.Hu("yt-remote-receiver-resumed","cast-selector-receiver")})),U7.push(g.Du("yt-remote-cast2-session-change",Hka)),U7.push(g.Du("yt-remote-connection-change",function(a){a?k7(S7(),"YouTube TV"):W7()||(k7(null,null),g7())})),a=X7(),b.isAuto&&(a.id+="#dial"),g.tu("desktop_enable_autoplay")&&(a.capabilities=["atp"]),a.name=b.device,a.app=b.app,(k=b.theme)&&(a.theme=k),T7(" -- with channel params: "+
g.Kg(a)),Ika(a),c.start(),S7()||Jka())},Lka=function(){var a=Y7();
e7()&&g.Fv("yt-remote-cast-available")&&a.push({key:"cast-selector-receiver",name:"Cast..."});return a},Y7=function(){var a=R7().zc.$_gos();
var b=Z7();b&&$7()&&(J4(a,b)||a.push(b));return Sja(a)},a8=function(){var a=Mka();
!a&&e7()&&f7()&&(a={key:"cast-selector-receiver",name:f7()});return a},Mka=function(){var a=Y7(),b=Z7();
b||(b=W7());return g.Oa(a,function(a){return b&&D4(b,a.key)?!0:!1})},Z7=function(){var a=S7();
if(!a)return null;var b=R7().td();return K4(b,a)},Hka=function(a){T7("remote.onCastSessionChange_: "+G4(a));
if(a){var b=Z7();b&&b.id==a.id?k7(b.id,"YouTube TV"):(b&&b8(),c8(a,1))}else $7()&&b8()},b8=function(){i7()?b7().stopSession():Z6("stopSession called before API ready.");
var a=$7();a&&(a.disconnect(1),d8(null))},e8=function(){var a=$7();
return!!a&&3!=a.getProxyState()},T7=function(a){l6("remote",a)},R7=function(){if(!f8){var a=g.z("yt.mdx.remote.screenService_");
f8=a?new O7(a):null}return f8},S7=function(){return g.z("yt.mdx.remote.currentScreenId_")},g8=function(a){g.y("yt.mdx.remote.currentScreenId_",a,void 0)},h8=function(){return g.z("yt.mdx.remote.connectData_")},V7=function(a){g.y("yt.mdx.remote.connectData_",a,void 0)},$7=function(){return g.z("yt.mdx.remote.connection_")},d8=function(a){var b=$7();
V7(null);a||g8("");g.y("yt.mdx.remote.connection_",a,void 0);Q7&&((0,g.D)(Q7,function(b){b(a)}),Q7.length=0);
b&&!a?g.Hu("yt-remote-connection-change",!1):!b&&a&&g.Hu("yt-remote-connection-change",!0)},W7=function(){var a=g.Hv();
if(!a)return null;var b=R7().td();return K4(b,a)},c8=function(a,b){Z7()&&Z7();
g8(a.id);var c=new D7(P7,a,X7());c.connect(b,h8());c.subscribe("beforeDisconnect",function(a){g.Hu("yt-remote-before-disconnect",a)});
c.subscribe("beforeDispose",function(){$7()&&d8(null)});
d8(c)},Jka=function(){var a=W7();
a?(T7("Resume connection to: "+G4(a)),c8(a,0)):(T4(),g7(),T7("Skipping connecting because no session screen found."))},Gka=function(){var a=X7();
if(g.fc(a)){a=O4();var b=g.Fv("yt-remote-session-name")||"",c=g.Fv("yt-remote-session-app")||"";a={device:"REMOTE_CONTROL",id:a,name:b,app:c,mdxVersion:3};g.y("yt.mdx.remote.channelParams_",a,void 0)}},X7=function(){return g.z("yt.mdx.remote.channelParams_")||{}},Ika=function(a){a?(g.Ev("yt-remote-session-app",a.app),g.Ev("yt-remote-session-name",a.name)):(g.Gv("yt-remote-session-app"),g.Gv("yt-remote-session-name"));
g.y("yt.mdx.remote.channelParams_",a,void 0)},i8=function(a,b,c){g.I.call(this);
this.G=a;this.l=b;this.o=new g.ku(this);g.J(this,this.o);this.o.M(b,"onCaptionsTrackListChanged",this.ZG);this.o.M(b,"captionschanged",this.TF);this.o.M(b,"captionssettingschanged",this.ax);this.o.M(b,"videoplayerreset",this.nl);this.o.M(b,"mdxautoplaycancel",this.Cz);this.V=this.o.M(b,"onVolumeChange",this.yv);this.F=!1;this.g=c;c.subscribe("proxyStateChange",this.Hv,this);c.subscribe("remotePlayerChange",this.dj,this);c.subscribe("remoteQueueChange",this.nl,this);c.subscribe("autoplayUpNext",this.ev,
this);c.subscribe("previousNextChange",this.Ev,this);c.subscribe("nowAutoplaying",this.Av,this);c.subscribe("autoplayDismissed",this.dv,this);this.suggestion=null;this.I=new g.aE(64);this.A=new g.N(this.Xw,500,this);g.J(this,this.A);this.B=new g.N(this.Yw,1E3,this);g.J(this,this.B);this.L=new d5(this.uK,0,this);g.J(this,this.L);this.C={};this.P=new g.N(this.Kx,1E3,this);g.J(this,this.P);this.K=new g.sm(this.QD,1E3,this);g.J(this,this.K);this.R=g.wa;this.ax();this.nl();this.dj()},j8=function(a,b){var c=
a.G,d=a.l.Z().lengthSeconds;
c.F=b||0;c.g.O("progresssync",b,d)},l8=function(a){j8(a,0);
a.A.stop();k8(a,new g.aE(64))},n8=function(a,b){if(m8(a)&&!a.F){var c=null;
b&&(c={style:a.l.Jg()},g.mc(c,b));a.g.Rw(a.l.Z(1).videoId,c);a.C=v7(a.g).l}},o8=function(a,b){var c=a.l.Fe();
if(c){var d=c.Qa;var e=c.listId.toString()}var f=a.l.Z(1);c=a.g;var k=f.videoId,l=d;d=f.playerParams;f=f.uh;var m=v7(c),n=e||m.listId;l=l||0;var q={videoId:k,currentIndex:l};q7(m,k,l);g.t(b)&&(o7(m,b),q.currentTime=b);g.t(n)&&(q.listId=n);null!=d&&(q.playerParams=d);null!=f&&(q.clickTrackingParams=f);A7(c,"setPlaylist",q);e||y7(c,m);k8(a,new g.aE(1))},p8=function(a,b){if(b){var c=a.l.Ob("captions","tracklist",{Es:1});
c&&c.length?(a.l.Wc("captions","track",b),a.F=!1):(a.l.Bh("captions"),a.F=!0)}else a.l.Wc("captions","track",{})},m8=function(a){return v7(a.g).videoId==a.l.Z(1).videoId},k8=function(a,b){a.B.stop();
var c=a.I;if(!g.iE(c,b)){var d=g.U(b,2);d!=g.U(a.I,2)&&g.qK(a.l,d);a.I=b;q8(a.G,c,b)}},s8=function(a){g.S.call(this,{D:"div",
J:"ytp-remote",H:[{D:"div",J:"ytp-remote-display-status",H:[{D:"div",J:"ytp-remote-display-status-icon",H:[g.eO()]},{D:"div",J:"ytp-remote-display-status-text",H:["{{statustext}}"]}]}]});this.g=new g.$O(this,250);g.J(this,this.g);this.l=a;this.M(a,"presentingplayerstatechange",this.o);r8(this,g.nK(a))},r8=function(a,b){if(3==a.l.Fa()){var c={RECEIVER_NAME:a.l.Ob("remote","currentReceiver").name};
c=g.U(b,128)?g.Q("YTP_MDX_STATUS_ERROR_2",c):g.jE(b)||g.U(b,4)?g.Q("YTP_MDX_STATUS_PLAYING_2",c):g.Q("YTP_MDX_STATUS_CONNECTED_2",c);a.updateValue("statustext",c);a.g.show()}else a.g.hide()},t8=function(a,b){g.tT.call(this,g.Q("YTP_MDX_TITLE"),0,a,b);
this.g=a;this.F={};this.M(a,"onMdxReceiversChange",this.I);this.M(a,"presentingplayerstatechange",this.I);this.I()},u8=function(a){g.TK.call(this,a);
g.Jv({YTP_MDX_CAST_SELECTOR:"Cast...",YTP_MDX_MY_COMPUTER:"This computer",YTP_MDX_PLAYER_ERROR:"This video is not available for remote playback.",YTP_MDX_STATUS_CONNECTED_2:"Connected to $RECEIVER_NAME",YTP_MDX_STATUS_ERROR_2:"Error on $RECEIVER_NAME",YTP_MDX_STATUS_PLAYING_2:"Playing on $RECEIVER_NAME",YTP_MDX_TITLE:"Play on"});this.o={key:I4(),name:g.Q("YTP_MDX_MY_COMPUTER")};this.B=null;this.C=[];this.K=this.l=null;this.I=[this.o];this.A=this.o;this.G=new g.aE(64);this.F=0;if(!g.DB(g.W(this.g))){a=
this.g;var b=g.cx(a);b&&(b=b.Ok())&&(b=new t8(a,b),g.J(this,b));b=new s8(a);g.J(this,b);g.IK(a,b.element,4)}},q8=function(a,b,c){a.G=c;
a.g.O("presentingplayerstatechange",new g.pE(c,b))},v8=function(a,b){if(b.key!=a.A.key)if(b.key==a.o.key)b8();
else{a.A=b;var c=a.g.getPlaylistId();var d=a.g.Z(1),e=d.videoId;if(c||e){var f=a.g.Fe();if(f){var k=[];for(var l=0;l<f.getLength();l++)k[l]=f.Eb(l).videoId}else k=[e];f=a.g.ya(1);c={videoIds:k,listId:c,videoId:e,playerParams:d.playerParams,clickTrackingParams:d.uh,index:Math.max(a.g.Kt(),0),currentTime:0==f?void 0:f}}else c=null;T7("Connecting to: "+g.Kg(b));"cast-selector-receiver"==b.key?(V7(c||null),i7()?b7().setLaunchParams(c||null):Z6("setLaunchParams called before ready.")):!c&&e8()&&S7()==
b.key?g.Hu("yt-remote-connection-change",!0):(b8(),V7(c||null),c=R7().td(),(c=K4(c,b.key))&&c8(c,1))}},Jja=/^https?$/i,Nka=["POST",
"PUT"];g.C(x4,g.Df);g.h=x4.prototype;
g.h.send=function(a,b,c,d){if(this.g)throw Error("[goog.net.XhrIo] Object is active with another request="+this.I+"; newUri="+a);b=b?b.toUpperCase():"GET";this.I=a;this.B="";this.A=0;this.ba=b;this.V=!1;this.l=!0;this.g=this.R?p4(this.R):p4(g.VW);this.P=this.R?o4(this.R):o4(g.VW);this.g.onreadystatechange=(0,g.A)(this.gs,this);try{m4(q4(this,"Opening Xhr")),this.W=!0,this.g.open(b,String(a),!0),this.W=!1}catch(f){m4(q4(this,"Error opening Xhr: "+f.message));u4(this,f);return}a=c||"";var e=this.headers.clone();
d&&Gja(d,function(a,b){e.set(b,a)});
d=g.Oa(e.qd(),Hja);c=g.x.FormData&&a instanceof g.x.FormData;!g.Sa(Nka,b)||d||c||e.set("Content-Type","application/x-www-form-urlencoded;charset=utf-8");e.forEach(function(a,b){this.g.setRequestHeader(b,a)},this);
this.da&&(this.g.responseType=this.da);"withCredentials"in this.g&&this.g.withCredentials!==this.X&&(this.g.withCredentials=this.X);try{r4(this),0<this.C&&(this.L=Ija(this.g),m4(q4(this,"Will abort after "+this.C+"ms if incomplete, xhr2 "+this.L)),this.L?(this.g.timeout=this.C,this.g.ontimeout=(0,g.A)(this.hs,this)):this.F=g.zg(this.hs,this.C,this)),m4(q4(this,"Sending request")),this.G=!0,this.g.send(a),this.G=!1}catch(f){m4(q4(this,"Send error: "+f.message)),u4(this,f)}};
g.h.hs=function(){"undefined"!=typeof g.xW&&this.g&&(this.B="Timed out after "+this.C+"ms, aborting",this.A=8,q4(this,this.B),this.dispatchEvent("timeout"),this.abort(8))};
g.h.abort=function(a){this.g&&this.l&&(q4(this,"Aborting"),this.l=!1,this.o=!0,this.g.abort(),this.o=!1,this.A=a||7,this.dispatchEvent("complete"),this.dispatchEvent("abort"),t4(this))};
g.h.T=function(){this.g&&(this.l&&(this.l=!1,this.o=!0,this.g.abort(),this.o=!1),t4(this,!0));x4.xa.T.call(this)};
g.h.gs=function(){this.ga()||(this.W||this.G||this.o?w4(this):this.aI())};
g.h.aI=function(){w4(this)};
g.h.isActive=function(){return!!this.g};
g.h.getStatus=function(){try{return 2<v4(this)?this.g.status:-1}catch(a){return-1}};
var s5={"\x00":"\\0","\b":"\\b","\f":"\\f","\n":"\\n","\r":"\\r","\t":"\\t","\x0B":"\\x0B",'"':'\\"',"\\":"\\\\","<":"<"},r5={"'":"\\'"},Oka={};g.h=z4.prototype;g.h.isEmpty=function(){return 0==this.g.length&&0==this.l.length};
g.h.clear=function(){this.g=[];this.l=[]};
g.h.contains=function(a){return g.Sa(this.g,a)||g.Sa(this.l,a)};
g.h.remove=function(a){var b=this.g;var c=(0,g.Dfa)(b,a);0<=c?(g.Wa(b,c),b=!0):b=!1;return b||g.Xa(this.l,a)};
g.h.jc=function(){for(var a=[],b=this.g.length-1;0<=b;--b)a.push(this.g[b]);var c=this.l.length;for(b=0;b<c;++b)a.push(this.l[b]);return a};
var Qja={cL:"atp",nN:"ska",bN:"que",AM:"mus",mN:"sus",TL:"dsp"};B4.prototype.Vj=function(){var a=new B4({id:this.id,name:this.name,app:this.app,type:this.type,user:this.username,userAvatarUri:this.avatar,obfuscatedGaiaId:this.obfuscatedGaiaId,theme:this.theme,capabilities:Array.from(this.capabilities.values()).join(","),experiments:Array.from(this.experiments.values()).join(",")});a.o=this.o;a.l=this.l;a.g=this.g};
var U4,N4="",a5=W4("loadGamesSDK")?"/cast_game_sender.js":"/cast_sender.js",aka=W4("loadCastFramework")||W4("loadCastApplicationFramework"),uka=["pkedcjkdefgpdelpbcmbmeomcjbeemfm","enhhojjnijigcajfphajepfemndkmdlo"];g.C(d5,g.I);g.h=d5.prototype;g.h.dA=function(a){this.A=arguments;this.g=!1;this.Aa?this.o=(0,g.E)()+this.Ac:this.Aa=g.zg(this.B,this.Ac)};
g.h.stop=function(){this.Aa&&(g.x.clearTimeout(this.Aa),this.Aa=null);this.o=null;this.g=!1;this.A=[]};
g.h.pause=function(){++this.l};
g.h.resume=function(){this.l&&(--this.l,!this.l&&this.g&&(this.g=!1,this.C.apply(null,this.A)))};
g.h.T=function(){this.stop();d5.xa.T.call(this)};
g.h.eA=function(){this.o?(this.Aa=g.zg(this.B,this.o-(0,g.E)()),this.o=null):(this.Aa=null,this.l?this.g=!0:(this.g=!1,this.C.apply(null,this.A)))};e5.prototype.stringify=function(a){return g.x.JSON.stringify(a,void 0)};
e5.prototype.parse=function(a){return g.x.JSON.parse(a,void 0)};g.h=f5.prototype;g.h.xg=null;g.h.fe=!1;g.h.Vh=null;g.h.Sp=null;g.h.Jh=null;g.h.qh=null;g.h.Hf=null;g.h.Zf=null;g.h.Ng=null;g.h.hc=null;g.h.rj=0;g.h.ge=null;g.h.Sl=null;g.h.If=null;g.h.Ai=-1;g.h.Dw=!0;g.h.pg=!1;g.h.an=0;g.h.vl=null;var m5={},k5={};g.h=f5.prototype;g.h.setTimeout=function(a){this.A=a};
g.h.EJ=function(a){a=a.target;var b=this.vl;b&&3==v4(a)?b.oh():this.Rx(a)};
g.h.Rx=function(a){try{if(a==this.hc)a:{var b=v4(this.hc),c=this.hc.A,d=this.hc.getStatus();if(g.Gd&&!g.Bc(10)||g.Id&&!g.zc("420+")){if(4>b)break a}else if(3>b||3==b&&!g.Lh&&!y4(this.hc))break a;this.pg||4!=b||7==c||(8==c||0>=d?this.g.de(3):this.g.de(2));w5(this);var e=this.hc.getStatus();this.Ai=e;var f=y4(this.hc);(this.fe=200==e)?(4==b&&o5(this),this.B?(q5(this,b,f),g.Lh&&this.fe&&3==b&&(this.ca.fa(this.l,"tick",this.AJ),this.l.start())):n5(this,f),this.fe&&!this.pg&&(4==b?this.g.kl(this):(this.fe=
!1,j5(this)))):(400==e&&0<f.indexOf("Unknown SID")?(this.If=3,l5(13)):(this.If=0,l5(14)),o5(this),p5(this))}}catch(k){this.hc&&y4(this.hc)}finally{}};
g.h.AJ=function(){var a=v4(this.hc),b=y4(this.hc);this.rj<b.length&&(w5(this),q5(this,a,b),this.fe&&4!=a&&j5(this))};
g.h.VI=function(a){v5((0,g.A)(this.UI,this,a),0)};
g.h.UI=function(a){this.pg||(w5(this),n5(this,a),j5(this))};
g.h.Ov=function(a){v5((0,g.A)(this.TI,this,a),0)};
g.h.TI=function(a){this.pg||(o5(this),this.fe=a,this.g.kl(this),this.g.de(4))};
g.h.cancel=function(){this.pg=!0;o5(this)};
g.h.iJ=function(){this.Vh=null;var a=(0,g.E)();0<=a-this.Sp?(2!=this.qh&&this.g.de(3),o5(this),this.If=2,l5(18),p5(this)):u5(this,this.Sp-a)};g.h=A5.prototype;g.h.Xm=null;g.h.Ad=null;g.h.wl=!1;g.h.es=null;g.h.gk=null;g.h.Ym=null;g.h.Zm=null;g.h.Jd=null;g.h.Xe=-1;g.h.zi=null;g.h.ci=null;g.h.connect=function(a){this.Zm=a;a=B5(this.g,null,this.Zm);l5(3);this.es=(0,g.E)();var b=this.g.G;null!=b?(this.zi=b[0],(this.ci=b[1])?(this.Jd=1,C5(this)):(this.Jd=2,E5(this))):(l4(a,"MODE","init"),this.Ad=new f5(this,void 0,void 0,void 0),this.Ad.xg=this.Xm,i5(this.Ad,a,!1,null,!0),this.Jd=0)};
g.h.Dz=function(a){if(a)this.Jd=2,E5(this);else{l5(4);var b=this.g;b.te=b.Af.Xe;Y5(b,9)}a&&this.de(2)};
g.h.Fm=function(a){return this.g.Fm(a)};
g.h.abort=function(){this.Ad&&(this.Ad.cancel(),this.Ad=null);this.Xe=-1};
g.h.ds=function(){return!1};
g.h.Iv=function(a,b){this.Xe=a.Ai;if(0==this.Jd)if(b){try{var c=this.l.parse(b)}catch(d){c=this.g;c.te=this.Xe;Y5(c,2);return}this.zi=c[0];this.ci=c[1]}else c=this.g,c.te=this.Xe,Y5(c,2);else if(2==this.Jd)if(this.wl)l5(7),this.Ym=(0,g.E)();else if("11111"==b){if(l5(6),this.wl=!0,this.gk=(0,g.E)(),c=this.gk-this.es,!g.Gd||g.Bc(10)||500>c)this.Xe=200,this.Ad.cancel(),l5(12),D5(this.g,this,!0)}else l5(8),this.gk=this.Ym=(0,g.E)(),this.wl=!1};
g.h.kl=function(){this.Xe=this.Ad.Ai;if(this.Ad.fe)0==this.Jd?this.ci?(this.Jd=1,C5(this)):(this.Jd=2,E5(this)):2==this.Jd&&((!g.Gd||g.Bc(10)?!this.wl:200>this.Ym-this.gk)?(l5(11),D5(this.g,this,!1)):(l5(12),D5(this.g,this,!0)));else{0==this.Jd?l5(9):2==this.Jd&&l5(10);var a=this.g;a.te=this.Xe;Y5(a,2)}};
g.h.lj=function(){return this.g.lj()};
g.h.isActive=function(){return this.g.isActive()};
g.h.de=function(a){this.g.de(a)};g.h=F5.prototype;g.h.ki=null;g.h.gd=null;g.h.Kb=null;g.h.Wm=null;g.h.jk=null;g.h.Gq=null;g.h.wk=null;g.h.Zi=0;g.h.oF=0;g.h.Ic=null;g.h.Df=null;g.h.Re=null;g.h.sg=null;g.h.Af=null;g.h.Rl=null;g.h.wh=-1;g.h.Ts=-1;g.h.te=-1;g.h.lh=0;g.h.eh=0;g.h.qg=8;var Z5=new g.Df;g.C(G5,g.$e);g.C(H5,g.$e);g.C(I5,g.$e);g.h=F5.prototype;g.h.connect=function(a,b,c,d,e){l5(0);this.Wm=b;this.ki=c||{};d&&g.t(e)&&(this.ki.OSID=d,this.ki.OAID=e);this.C?(v5((0,g.A)(this.gr,this,a),100),O5(this)):this.gr(a)};
g.h.gr=function(a){this.Af=new A5(this);this.Af.Xm=null;this.Af.l=this.B;this.Af.connect(a)};
g.h.ds=function(){return 0==this.g};
g.h.Mv=function(a){this.Df=null;T5(this,a)};
g.h.Lv=function(){this.Re=null;this.Kb=new f5(this,this.o,"rpc",this.F);this.Kb.xg=null;this.Kb.an=0;var a=this.Gq.clone();g.np(a,"RID","rpc");g.np(a,"SID",this.o);g.np(a,"CI",this.Rl?"0":"1");g.np(a,"AID",this.wh);K5(this,a);if(!g.Gd||g.Bc(10))g.np(a,"TYPE","xmlhttp"),i5(this.Kb,a,!0,this.wk,!1);else{g.np(a,"TYPE","html");var b=this.Kb,c=!!this.wk;b.qh=3;b.Hf=k4(a.clone());t5(b,c)}};
g.h.Iv=function(a,b){if(0!=this.g&&(this.Kb==a||this.gd==a))if(this.te=a.Ai,this.gd==a&&3==this.g)if(7<this.qg){try{var c=this.B.parse(b)}catch(f){c=null}if(g.za(c)&&3==c.length)if(0==c[0])a:{if(!this.Re){if(this.Kb)if(this.Kb.Jh+3E3<this.gd.Jh)P5(this),this.Kb.cancel(),this.Kb=null;else break a;W5(this);l5(19)}}else this.Ts=c[1],0<this.Ts-this.wh&&37500>c[2]&&this.Rl&&0==this.eh&&!this.sg&&(this.sg=v5((0,g.A)(this.PF,this),6E3));else Y5(this,11)}else b!=Oka.DL.g&&Y5(this,11);else if(this.Kb==a&&
P5(this),!g.sb(b)){c=this.B.parse(b);g.za(c);for(var d=0;d<c.length;d++){var e=c[d];this.wh=e[0];e=e[1];2==this.g?"c"==e[0]?(this.o=e[1],this.wk=e[2],e=e[3],null!=e?this.qg=e:this.qg=6,this.g=3,this.Ic&&this.Ic.Qq(),this.Gq=B5(this,this.lj()?this.wk:null,this.Wm),U5(this)):"stop"==e[0]&&Y5(this,7):3==this.g&&("stop"==e[0]?Y5(this,7):"noop"!=e[0]&&this.Ic&&this.Ic.Pq(e),this.eh=0)}}};
g.h.PF=function(){null!=this.sg&&(this.sg=null,this.Kb.cancel(),this.Kb=null,W5(this),l5(20))};
g.h.kl=function(a){if(this.Kb==a){P5(this);this.Kb=null;var b=2}else if(this.gd==a)this.gd=null,b=1;else return;this.te=a.Ai;if(0!=this.g)if(a.fe)1==b?(b=(0,g.E)()-a.Jh,Z5.dispatchEvent(new H5(Z5,a.Ng?a.Ng.length:0,b,this.lh)),N5(this),this.A.length=0):U5(this);else{var c=a.If,d;if(!(d=3==c||7==c||0==c&&0<this.te)){if(d=1==b)this.gd||this.Df||1==this.g||2<=this.lh?d=!1:(this.Df=v5((0,g.A)(this.Mv,this,a),V5(this,this.lh)),this.lh++,d=!0);d=!(d||2==b&&W5(this))}if(d)switch(c){case 1:Y5(this,5);break;
case 4:Y5(this,10);break;case 3:Y5(this,6);break;case 7:Y5(this,12);break;default:Y5(this,2)}}};
g.h.Oz=function(a){if(!g.Sa(arguments,this.g))throw Error("Unexpected channel state: "+this.g);};
g.h.kK=function(a){a?l5(2):(l5(1),X5(this,8))};
g.h.Fm=function(a){if(a)throw Error("Can't create secondary domain capable XhrIo object.");a=new x4;a.X=!1;return a};
g.h.isActive=function(){return!!this.Ic&&this.Ic.isActive(this)};
g.h.de=function(a){Z5.dispatchEvent(new I5(Z5,a))};
g.h.lj=function(){return!(!g.Gd||g.Bc(10))};
g.h=$5.prototype;g.h.Qq=function(){};
g.h.Pq=function(){};
g.h.Oq=function(){};
g.h.ym=function(){};
g.h.Kr=function(){return{}};
g.h.isActive=function(){return!0};g.C(a6,g.I);g.h=a6.prototype;g.h.NI=function(){this.Ac=Math.min(3E5,2*this.Ac);this.o();this.l&&this.start()};
g.h.start=function(){var a=this.Ac+15E3*Math.random();g.Pq(this.g,a);this.l=(0,g.E)()+a};
g.h.stop=function(){this.g.stop();this.l=0};
g.h.isActive=function(){return this.g.isActive()};
g.h.reset=function(){this.g.stop();this.Ac=5E3};g.C(b6,$5);g.h=b6.prototype;g.h.subscribe=function(a,b,c){return this.o.subscribe(a,b,c)};
g.h.unsubscribe=function(a,b,c){return this.o.unsubscribe(a,b,c)};
g.h.Fc=function(a){return this.o.Fc(a)};
g.h.O=function(a,b){return this.o.O.apply(this.o,arguments)};
g.h.dispose=function(){this.K||(this.K=!0,g.Ye(this.o),c6(this),g.Ye(this.l),this.l=null)};
g.h.ga=function(){return this.K};
g.h.connect=function(a,b,c){if(!this.g||2!=this.g.g){this.I="";this.l.stop();this.B=a||null;this.A=b||0;a=this.L+"/test";b=this.L+"/bind";var d=new F5(c?c.firstTestResults:null,c?c.secondTestResults:null,this.P),e=this.g;e&&(e.Ic=null);d.Ic=this;this.g=d;e?this.g.connect(a,b,this.C,e.o,e.wh):c?this.g.connect(a,b,this.C,c.sessionId,c.arrayId):this.g.connect(a,b,this.C)}};
g.h.sendMessage=function(a,b){var c={_sc:a};b&&g.mc(c,b);this.l.isActive()||2==(this.g?this.g.g:0)?this.F.push(c):d6(this)&&Q5(this.g,c)};
g.h.Qq=function(){this.l.reset();this.B=null;this.A=0;if(this.F.length){var a=this.F;this.F=[];for(var b=0,c=a.length;b<c;++b)Q5(this.g,a[b])}this.O("handlerOpened")};
g.h.Oq=function(a){var b=2==a&&401==this.g.te;4==a||b||this.l.start();this.O("handlerError",a)};
g.h.ym=function(a){if(!this.l.isActive())this.O("handlerClosed");else if(a)for(var b=0,c=a.length;b<c;++b){var d=a[b].map;d&&this.F.push(d)}};
g.h.Kr=function(){var a={v:2};this.I&&(a.gsessionid=this.I);0!=this.A&&(a.ui=""+this.A);0!=this.G&&(a.ui=""+this.G);this.B&&g.mc(a,this.B);return a};
g.h.Pq=function(a){"S"==a[0]?this.I=a[1]:"gracefulReconnect"==a[0]?(this.l.start(),M5(this.g)):this.O("handlerMessage",new fka(a[0],a[1]))};
g.h.JK=function(){this.l.isActive();var a=this.g,b=0;a.Kb&&b++;a.gd&&b++;0!=b||this.connect(this.B,this.A)};e6.prototype.A=function(a,b,c,d){b?a(d):a({text:c.responseText})};
e6.prototype.o=function(a,b){a(Error("Request error: "+b.status))};
e6.prototype.B=function(a){a(Error("request timed out"))};var lka=(0,g.E)(),j6=null,n6=Array(50),m6=-1,o6=!1;g.C(p6,g.P);p6.prototype.td=function(){return this.g};
p6.prototype.contains=function(a){return!!J4(this.g,a)};
p6.prototype.get=function(a){return a?K4(this.g,a):null};
p6.prototype.info=function(a){l6(this.F,a)};g.C(r6,g.P);var w8=[2E3,2E3,1E3,1E3,1E3,2E3,2E3,5E3,5E3,1E4];g.h=r6.prototype;g.h.start=function(){!this.g&&(0,window.isNaN)(this.Aa)&&this.Wx()};
g.h.stop=function(){this.g&&(this.g.abort(),this.g=null);(0,window.isNaN)(this.Aa)||(g.ys(this.Aa),this.Aa=window.NaN)};
g.h.T=function(){this.stop();r6.xa.T.call(this)};
g.h.Wx=function(){this.Aa=window.NaN;this.g=g.Ns(f6(this.C,"/pairing/get_screen"),{method:"POST",gb:{pairing_code:this.B},timeout:5E3,ob:(0,g.A)(this.LK,this),onError:(0,g.A)(this.KK,this),Yc:(0,g.A)(this.MK,this)})};
g.h.LK=function(a,b){this.g=null;var c=b.screen||{};c.dialId=this.o;c.name=this.A;this.O("pairingComplete",new C4(c))};
g.h.KK=function(a){this.g=null;a.status&&404==a.status?this.l>=w8.length?this.O("pairingFailed",Error("DIAL polling timed out")):(a=w8[this.l],this.Aa=g.ws((0,g.A)(this.Wx,this),a),this.l++):this.O("pairingFailed",Error("Server error "+a.status))};
g.h.MK=function(){this.g=null;this.O("pairingFailed",Error("Server not responding"))};g.C(t6,p6);g.h=t6.prototype;g.h.start=function(){s6(this)&&this.O("screenChange");!g.Fv("yt-remote-lounge-token-expiration")&&u6(this);g.ys(this.l);this.l=g.ws((0,g.A)(this.start,this),1E4)};
g.h.add=function(a,b){s6(this);q6(this,a);v6(this,!1);this.O("screenChange");b(a);a.token||u6(this)};
g.h.remove=function(a,b){var c=s6(this);nka(this,a)&&(v6(this,!1),c=!0);b(a);c&&this.O("screenChange")};
g.h.Nl=function(a,b,c,d){var e=s6(this),f=this.get(a.id);f?(f.name!=b&&(f.name=b,v6(this,!1),e=!0),c(a)):d(Error("no such local screen."));e&&this.O("screenChange")};
g.h.T=function(){g.ys(this.l);t6.xa.T.call(this)};
g.h.pA=function(a){s6(this);var b=this.g.length;a=a&&a.screens||[];for(var c=0,d=a.length;c<d;++c){var e=a[c],f=this.get(e.screenId);f&&(f.token=e.loungeToken,--b)}v6(this,!b);b&&l6(this.F,"Missed "+b+" lounge tokens.")};
g.h.oA=function(a){l6(this.F,"Requesting lounge tokens failed: "+a)};g.C(x6,g.P);g.h=x6.prototype;g.h.start=function(){var a=(0,window.parseInt)(g.Fv("yt-remote-fast-check-period")||"0",10);(this.A=(0,g.E)()-144E5<a?0:a)?A6(this):(this.A=(0,g.E)()+3E5,g.Ev("yt-remote-fast-check-period",this.A),this.gp())};
g.h.isEmpty=function(){return g.fc(this.g)};
g.h.update=function(){w6("Updating availability on schedule.");var a=this.C(),b=g.Vb(this.g,function(b,d){return b&&!!K4(a,d)},this);
z6(this,b)};
g.h.T=function(){g.ys(this.o);this.o=window.NaN;this.l&&(this.l.abort(),this.l=null);x6.xa.T.call(this)};
g.h.gp=function(){g.ys(this.o);this.o=window.NaN;this.l&&this.l.abort();var a=B6(this);if(g.Yb(a)){var b=f6(this.B,"/pairing/get_screen_availability");this.l=g6(this.B,b,{lounge_token:g.$b(a).join(",")},(0,g.A)(this.uI,this,a),(0,g.A)(this.tI,this))}else z6(this,{}),A6(this)};
g.h.uI=function(a,b){this.l=null;var c=g.$b(B6(this));if(g.lb(c,g.$b(a))){c=b.screens||[];for(var d={},e=0,f=c.length;e<f;++e)d[a[c[e].loungeToken]]="online"==c[e].status;z6(this,d);A6(this)}else this.Cb("Changing Screen set during request."),this.gp()};
g.h.tI=function(a){this.Cb("Screen availability failed: "+a);this.l=null;A6(this)};
g.h.Cb=function(a){l6("OnlineScreenService",a)};g.C(C6,p6);g.h=C6.prototype;g.h.start=function(){this.o.start();this.l.start();this.g.length&&(this.O("screenChange"),this.l.isEmpty()||this.O("onlineScreenChange"))};
g.h.add=function(a,b,c){this.o.add(a,b,c)};
g.h.remove=function(a,b,c){this.o.remove(a,b,c);this.l.update()};
g.h.Nl=function(a,b,c,d){this.o.contains(a)?this.o.Nl(a,b,c,d):(a="Updating name of unknown screen: "+a.name,l6(this.F,a),d(Error(a)))};
g.h.td=function(a){return a?this.g:g.Za(this.g,(0,g.Vd)(this.A,function(a){return!this.contains(a)},this))};
g.h.Xx=function(){return(0,g.Vd)(this.td(!0),function(a){return!!this.l.g[a.id]},this)};
g.h.Yx=function(a,b,c,d,e){this.info("getDialScreenByPairingCode "+a+" / "+b);var f=new r6(this.C,a,b,c);f.subscribe("pairingComplete",(0,g.A)(function(a){g.Ye(f);d(D6(this,a))},this));
f.subscribe("pairingFailed",function(a){g.Ye(f);e(a)});
f.start();return(0,g.A)(f.stop,f)};
g.h.OK=function(a,b,c,d){g.Ns(f6(this.C,"/pairing/get_screen"),{method:"POST",gb:{pairing_code:a},timeout:5E3,ob:(0,g.A)(function(a,d){var e=new C4(d.screen||{});if(!e.name||F6(this,e.name)){a:{var f=e.name;for(var m=2,n=b(f,m);F6(this,n);){m++;if(20<m)break a;n=b(f,m)}f=n}e.name=f}c(D6(this,e))},this),
onError:(0,g.A)(function(a){d(Error("pairing request failed: "+a.status))},this),
Yc:(0,g.A)(function(){d(Error("pairing request timed out."))},this)})};
g.h.T=function(){g.Ye(this.o);g.Ye(this.l);C6.xa.T.call(this)};
g.h.CA=function(){G6(this);this.O("screenChange");this.l.update()};
C6.prototype.dispose=C6.prototype.dispose;g.C(I6,g.P);g.h=I6.prototype;g.h.ll=function(a){this.o=a;this.O("sessionScreen",this.o)};
g.h.yd=function(a){this.ga()||(a&&J6(this,""+a),this.o=null,this.O("sessionScreen",null))};
g.h.info=function(a){l6(this.P,a)};
g.h.ay=function(){return null};
g.h.pp=function(a){var b=this.l;a?(b.displayStatus=new window.chrome.cast.ReceiverDisplayStatus(a,[]),b.displayStatus.showStop=!0):b.displayStatus=null;window.chrome.cast.setReceiverDisplayStatus(b,(0,g.A)(function(){this.info("Updated receiver status for "+b.friendlyName+": "+a)},this),(0,g.A)(function(){J6(this,"Failed to update receiver status for: "+b.friendlyName)},this))};
g.h.T=function(){this.pp("");I6.xa.T.call(this)};g.C(L6,I6);g.h=L6.prototype;g.h.np=function(a){if(this.g){if(this.g==a)return;J6(this,"Overriding cast sesison with new session object");this.g.removeUpdateListener(this.C);this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B)}this.g=a;this.g.addUpdateListener(this.C);this.g.addMessageListener("urn:x-cast:com.google.youtube.mdx",this.B);rka(this)};
g.h.yh=function(a){this.info("launchWithParams no-op for Cast: "+g.Kg(a))};
g.h.stop=function(){this.g?this.g.stop((0,g.A)(function(){this.yd()},this),(0,g.A)(function(){this.yd(Error("Failed to stop receiver app."))},this)):this.yd(Error("Stopping cast device witout session."))};
g.h.pp=g.wa;g.h.T=function(){this.info("disposeInternal");g.ys(this.A);this.A=0;this.g&&(this.g.removeUpdateListener(this.C),this.g.removeMessageListener("urn:x-cast:com.google.youtube.mdx",this.B));this.g=null;L6.xa.T.call(this)};
g.h.tJ=function(a,b){if(!this.ga())if(b){var c=g.cr(b);if(g.Ca(c)){var d=""+c.type;c=c.data||{};this.info("onYoutubeMessage_: "+d+" "+g.Kg(c));switch(d){case "mdxSessionStatus":K6(this,c.screenId);break;default:J6(this,"Unknown youtube message: "+d)}}else J6(this,"Unable to parse message.")}else J6(this,"No data in message.")};
g.h.Tr=function(a,b,c,d){E6(this.I,this.l.label,a,this.l.friendlyName,(0,g.A)(function(e){e?b(e):0<=d?(J6(this,"Screen "+a+" appears to be offline. "+d+" retries left."),g.ws((0,g.A)(this.Tr,this,a,b,c,d-1),300)):c(Error("Unable to fetch screen."))},this),c)};
g.h.ay=function(){return this.g};
g.h.PK=function(a){this.ga()||a||(J6(this,"Cast session died."),this.yd())};g.C(M6,I6);g.h=M6.prototype;g.h.np=function(a){this.A=a;this.A.addUpdateListener(this.L)};
g.h.yh=function(a){this.B=a;this.F()};
g.h.stop=function(){this.g();this.g=g.wa;g.ys(this.C);this.A?this.A.stop((0,g.A)(this.yd,this,null),(0,g.A)(this.yd,this,"Failed to stop DIAL device.")):this.yd()};
g.h.T=function(){this.g();this.g=g.wa;g.ys(this.C);this.A&&this.A.removeUpdateListener(this.L);this.A=null;M6.xa.T.call(this)};
g.h.SK=function(a){this.ga()||a||(J6(this,"DIAL session died."),this.g(),this.g=g.wa,this.yd())};
g.h.un=function(a){this.K=I4();if(this.B){var b=new window.chrome.cast.DialLaunchResponse(!0,O6(this));a(b);N6(this)}else this.F=(0,g.A)(function(){g.ys(this.C);this.F=g.wa;this.C=window.NaN;var b=new window.chrome.cast.DialLaunchResponse(!0,O6(this));a(b);N6(this)},this),this.C=g.ws((0,g.A)(function(){this.F()},this),100)};
g.h.YA=function(a,b,c){E6(this.I,this.G.receiver.label,a,this.l.friendlyName,(0,g.A)(function(a){a&&a.token?(this.ll(a),b(new window.chrome.cast.DialLaunchResponse(!1))):this.un(b,c)},this),(0,g.A)(function(a){J6(this,"Failed to get DIAL screen: "+a);
this.un(b,c)},this))};g.C(P6,I6);P6.prototype.stop=function(){this.yd()};
P6.prototype.np=g.wa;P6.prototype.yh=function(){g.ys(this.g);this.g=window.NaN;var a=K4(this.I.td(),this.l.label);a?this.ll(a):this.yd(Error("No such screen"))};
P6.prototype.T=function(){g.ys(this.g);this.g=window.NaN;P6.xa.T.call(this)};g.C(Q6,g.P);g.h=Q6.prototype;
g.h.init=function(a,b){window.chrome.cast.timeout.requestSession=3E4;var c=new window.chrome.cast.SessionRequest(this.F);this.G||(c.dialRequest=new window.chrome.cast.DialRequest("YouTube"));var d=window.chrome.cast.AutoJoinPolicy.TAB_AND_ORIGIN_SCOPED,e=a?window.chrome.cast.DefaultActionPolicy.CAST_THIS_TAB:window.chrome.cast.DefaultActionPolicy.CREATE_SESSION;c=new window.chrome.cast.ApiConfig(c,(0,g.A)(this.Jv,this),(0,g.A)(this.fI,this),d,e);c.customDialLaunchCallback=(0,g.A)(this.sG,this);window.chrome.cast.initialize(c,
(0,g.A)(function(){this.ga()||(window.chrome.cast.addReceiverActionListener(this.A),ika(),this.l.subscribe("onlineScreenChange",(0,g.A)(this.Zx,this)),this.o=V6(this),window.chrome.cast.setCustomReceivers(this.o,g.wa,(0,g.A)(function(a){this.Cb("Failed to set initial custom receivers: "+g.Kg(a))},this)),this.O("yt-remote-cast2-availability-change",T6(this)),b(!0))},this),(0,g.A)(function(a){this.Cb("Failed to initialize API: "+g.Kg(a));
b(!1)},this))};
g.h.ZJ=function(a,b){S6("Setting connected screen ID: "+a+" -> "+b);if(this.g){var c=this.g.o;if(!a||c&&c.id!=a)S6("Unsetting old screen status: "+this.g.l.friendlyName),U6(this,null)}if(a&&b){if(!this.g){c=K4(this.l.td(),a);if(!c){S6("setConnectedScreenStatus: Unknown screen.");return}var d=R6(this,c);d||(S6("setConnectedScreenStatus: Connected receiver not custom..."),d=new window.chrome.cast.Receiver(c.uuid?c.uuid:c.id,c.name),d.receiverType=window.chrome.cast.ReceiverType.CUSTOM,this.o.push(d),
window.chrome.cast.setCustomReceivers(this.o,g.wa,(0,g.A)(function(a){this.Cb("Failed to set initial custom receivers: "+g.Kg(a))},this)));
S6("setConnectedScreenStatus: new active receiver: "+d.friendlyName);U6(this,new P6(this.l,d),!0)}this.g.pp(b)}else S6("setConnectedScreenStatus: no screen.")};
g.h.aK=function(a){this.ga()?this.Cb("Setting connection data on disposed cast v2"):this.g?this.g.yh(a):this.Cb("Setting connection data without a session")};
g.h.RK=function(){this.ga()?this.Cb("Stopping session on disposed cast v2"):this.g?(this.g.stop(),U6(this,null)):S6("Stopping non-existing session")};
g.h.requestSession=function(){window.chrome.cast.requestSession((0,g.A)(this.Jv,this),(0,g.A)(this.AI,this))};
g.h.T=function(){this.l.unsubscribe("onlineScreenChange",(0,g.A)(this.Zx,this));window.chrome&&window.chrome.cast&&window.chrome.cast.removeReceiverActionListener(this.A);g.Xa(g.z("yt.mdx.remote.debug.handlers_")||[],h6);g.Ye(this.g);Q6.xa.T.call(this)};
g.h.Cb=function(a){l6("Controller",a)};
g.h.Kv=function(a,b){this.g==a&&(b||U6(this,null),this.O("yt-remote-cast2-session-change",b))};
g.h.bI=function(a,b){if(!this.ga())if(a)switch(a.friendlyName=window.chrome.cast.unescape(a.friendlyName),S6("onReceiverAction_ "+a.label+" / "+a.friendlyName+"-- "+b),b){case window.chrome.cast.ReceiverAction.CAST:if(this.g)if(this.g.l.label!=a.label)S6("onReceiverAction_: Stopping active receiver: "+this.g.l.friendlyName),this.g.stop();else{S6("onReceiverAction_: Casting to active receiver.");this.g.o&&this.O("yt-remote-cast2-session-change",this.g.o);break}switch(a.receiverType){case window.chrome.cast.ReceiverType.CUSTOM:U6(this,
new P6(this.l,a));break;case window.chrome.cast.ReceiverType.DIAL:U6(this,new M6(this.l,a,this.C));break;case window.chrome.cast.ReceiverType.CAST:U6(this,new L6(this.l,a));break;default:this.Cb("Unknown receiver type: "+a.receiverType)}break;case window.chrome.cast.ReceiverAction.STOP:this.g&&this.g.l.label==a.label?this.g.stop():this.Cb("Stopping receiver w/o session: "+a.friendlyName)}else this.Cb("onReceiverAction_ called without receiver.")};
g.h.sG=function(a){if(this.ga())return window.Promise.reject(Error("disposed"));var b=a.receiver;b.receiverType!=window.chrome.cast.ReceiverType.DIAL&&(this.Cb("Not DIAL receiver: "+b.friendlyName),b.receiverType=window.chrome.cast.ReceiverType.DIAL);var c=this.g?this.g.l:null;if(!c||c.label!=b.label)return this.Cb("Receiving DIAL launch request for non-clicked DIAL receiver: "+b.friendlyName),window.Promise.reject(Error("illegal DIAL launch"));if(c&&c.label==b.label&&c.receiverType!=window.chrome.cast.ReceiverType.DIAL){if(this.g.o)return S6("Reselecting dial screen."),
this.O("yt-remote-cast2-session-change",this.g.o),window.Promise.resolve(new window.chrome.cast.DialLaunchResponse(!1));this.Cb('Changing CAST intent from "'+c.receiverType+'" to "dial" for '+b.friendlyName);U6(this,new M6(this.l,b,this.C))}b=this.g;b.G=a;return b.G.appState==window.chrome.cast.DialAppState.RUNNING?new window.Promise((0,g.A)(b.YA,b,(b.G.extraData||{}).screenId||null)):new window.Promise((0,g.A)(b.un,b))};
g.h.Jv=function(a){if(!this.ga()){S6("New cast session ID: "+a.sessionId);var b=a.receiver;if(b.receiverType!=window.chrome.cast.ReceiverType.CUSTOM){if(!this.g)if(b.receiverType==window.chrome.cast.ReceiverType.CAST)S6("Got resumed cast session before resumed mdx connection."),b.friendlyName=window.chrome.cast.unescape(b.friendlyName),U6(this,new L6(this.l,b),!0);else{this.Cb("Got non-cast session without previous mdx receiver event, or mdx resume.");return}var c=this.g.l,d=K4(this.l.td(),c.label);
d&&D4(d,b.label)&&c.receiverType!=window.chrome.cast.ReceiverType.CAST&&b.receiverType==window.chrome.cast.ReceiverType.CAST&&(S6("onSessionEstablished_: manual to cast session change "+b.friendlyName),g.Ye(this.g),this.g=new L6(this.l,b),this.g.subscribe("sessionScreen",(0,g.A)(this.Kv,this,this.g)),this.g.yh(null));this.g.np(a)}}};
g.h.QK=function(){return this.g?this.g.ay():null};
g.h.AI=function(a){this.ga()||(this.Cb("Failed to estabilish a session: "+g.Kg(a)),a.code!=window.chrome.cast.ErrorCode.CANCEL&&U6(this,null))};
g.h.fI=function(a){S6("Receiver availability updated: "+a);if(!this.ga()){var b=T6(this);this.B=a==window.chrome.cast.ReceiverAvailability.AVAILABLE;T6(this)!=b&&this.O("yt-remote-cast2-availability-change",T6(this))}};
g.h.Zx=function(){this.ga()||(this.o=V6(this),S6("Updating custom receivers: "+g.Kg(this.o)),window.chrome.cast.setCustomReceivers(this.o,g.wa,(0,g.A)(function(){this.Cb("Failed to set custom receivers.")},this)),this.O("yt-remote-cast2-availability-change",T6(this)))};
Q6.prototype.setLaunchParams=Q6.prototype.aK;Q6.prototype.setConnectedScreenStatus=Q6.prototype.ZJ;Q6.prototype.stopSession=Q6.prototype.RK;Q6.prototype.getCastSession=Q6.prototype.QK;Q6.prototype.requestSession=Q6.prototype.requestSession;Q6.prototype.init=Q6.prototype.init;Q6.prototype.dispose=Q6.prototype.dispose;var d7=[];l7.prototype.reset=function(a){this.listId="";this.index=-1;this.videoId="";m7(this);this.volume=-1;this.muted=!1;a&&(this.index=a.index,this.listId=a.listId,this.videoId=a.videoId,this.g=a.playerState,this.volume=a.volume,this.muted=a.muted,this.audioTrackId=a.audioTrackId,this.l=a.trackData,this.ue=a.hasPrevious,this.hasNext=a.hasNext,this.G=a.playerTime,this.F=a.playerTimeAt,this.B=a.seekableStart,this.o=a.seekableEnd,this.I=a.duration,this.K=a.loadedTime,this.A=a.liveIngestionTime,this.C=!(0,window.isNaN)(this.A))};
l7.prototype.isAdPlaying=function(){return 1081==this.g};
l7.prototype.clone=function(){return new l7(r7(this))};g.C(u7,g.P);g.h=u7.prototype;g.h.play=function(){1==this.g?(this.l?this.l.play(null,g.wa,C7(this,"play")):A7(this,"play"),z7(this,1,p7(v7(this))),this.O("remotePlayerChange")):x7(this,this.play)};
g.h.pause=function(){1==this.g?(this.l?this.l.pause(null,g.wa,C7(this,"pause")):A7(this,"pause"),z7(this,2,p7(v7(this))),this.O("remotePlayerChange")):x7(this,this.pause)};
g.h.Vx=function(a){if(1==this.g){if(this.l){var b=v7(this),c=new window.chrome.cast.media.SeekRequest;c.currentTime=a;c.resumeState=1==b.g||3==b.g?window.chrome.cast.media.ResumeState.PLAYBACK_START:window.chrome.cast.media.ResumeState.PLAYBACK_PAUSE;this.l.seek(c,g.wa,C7(this,"seekTo",{newTime:a}))}else A7(this,"seekTo",{newTime:a});z7(this,3,a);this.O("remotePlayerChange")}else x7(this,g.B(this.Vx,a))};
g.h.stop=function(){if(1==this.g){this.l?this.l.stop(null,g.wa,C7(this,"stopVideo")):A7(this,"stopVideo");var a=v7(this);a.index=-1;a.videoId="";m7(a);y7(this,a);this.O("remotePlayerChange")}else x7(this,this.stop)};
g.h.setVolume=function(a,b){if(1==this.g){var c=v7(this);if(this.o){if(c.volume!=a){var d=Math.round(a)/100;this.o.setReceiverVolumeLevel(d,(0,g.A)(function(){l6("CP","set receiver volume: "+d)},this),(0,g.A)(function(){this.Cb("failed to set receiver volume.")},this))}c.muted!=b&&this.o.setReceiverMuted(b,(0,g.A)(function(){l6("CP","set receiver muted: "+b)},this),(0,g.A)(function(){this.Cb("failed to set receiver muted.")},this))}else{var e={volume:a,
muted:b};-1!=c.volume&&(e.delta=a-c.volume);A7(this,"setVolume",e)}c.muted=b;c.volume=a;y7(this,c)}else x7(this,g.B(this.setVolume,a,b))};
g.h.Rw=function(a,b){if(1==this.g){var c=v7(this),d={videoId:a};b&&(c.l={trackName:b.name,languageCode:b.languageCode,sourceLanguageCode:b.translationLanguage?b.translationLanguage.languageCode:"",languageName:b.languageName,format:b.format,kind:b.kind},d.style=g.Kg(b.style),g.mc(d,c.l));A7(this,"setSubtitlesTrack",d);y7(this,c)}else x7(this,g.B(this.Rw,a,b))};
g.h.Tp=function(a,b){if(1==this.g){A7(this,"setAudioTrack",{videoId:a,audioTrackId:b.qb.id});var c=v7(this);c.audioTrackId=b.qb.id;y7(this,c)}else x7(this,g.B(this.Tp,a,b))};
g.h.Ux=function(a,b){if(1==this.g){if(a&&b){var c=v7(this);q7(c,a,b);y7(this,c)}A7(this,"previous")}else x7(this,g.B(this.Ux,a,b))};
g.h.Tx=function(a,b){if(1==this.g){if(a&&b){var c=v7(this);q7(c,a,b);y7(this,c)}A7(this,"next")}else x7(this,g.B(this.Tx,a,b))};
g.h.xr=function(){1==this.g?A7(this,"dismissAutoplay"):x7(this,this.xr)};
g.h.dispose=function(){if(3!=this.g){var a=this.g;this.g=3;this.O("proxyStateChange",a,this.g)}u7.xa.dispose.call(this)};
g.h.T=function(){w7(this);this.A=null;this.B.clear();t7(this,null);u7.xa.T.call(this)};
g.h.Up=function(a){if((a!=this.g||2==a)&&3!=this.g&&0!=a){var b=this.g;this.g=a;this.O("proxyStateChange",b,a);if(1==a)for(;!this.B.isEmpty();)b=a=this.B,0==b.g.length&&(b.g=b.l,b.g.reverse(),b.l=[]),a.g.pop().apply(this);else 3==a&&this.dispose()}};
g.h.YH=function(a,b){this.O(a,b)};
g.h.VF=function(a){if(!a)this.cj(null),t7(this,null);else if(this.o.receiver.volume){a=this.o.receiver.volume;var b=v7(this),c=Math.round(100*a.level||0);if(b.volume!=c||b.muted!=a.muted)l6("CP","Cast volume update: "+a.level+(a.muted?" muted":"")),b.volume=c,b.muted=!!a.muted,y7(this,b)}};
g.h.cj=function(a){l6("CP","Cast media: "+!!a);this.l&&this.l.removeUpdateListener(this.G);if(this.l=a)this.l.addUpdateListener(this.G),B7(this),this.O("remotePlayerChange")};
g.h.UF=function(a){a?(B7(this),this.O("remotePlayerChange")):this.cj(null)};
g.h.iG=function(){var a=h7();a&&t7(this,a)};
g.h.Cb=function(a){l6("CP",a)};g.C(D7,g.P);g.h=D7.prototype;
g.h.connect=function(a,b){if(b){var c=b.listId,d=b.videoId,e=b.playerParams,f=b.clickTrackingParams,k=b.index,l={videoId:d},m=b.currentTime;g.t(m)&&(l.currentTime=5>=m?0:m);e&&(l.playerParams=e);f&&(l.clickTrackingParams=f);c&&(l.listId=c);g.t(k)&&(l.currentIndex=k);c&&(this.Na.listId=c);this.Na.videoId=d;this.Na.index=k||0;this.Na.state=3;o7(this.Na,m);this.A="UNSUPPORTED";E7("Connecting with setPlaylist and params: "+g.Kg(l));this.g.connect({method:"setPlaylist",params:g.Kg(l)},a,Q4())}else E7("Connecting without params"),
this.g.connect({},a,Q4());yka(this)};
g.h.dispose=function(){this.ga()||(this.O("beforeDispose"),F7(this,3));D7.xa.dispose.call(this)};
g.h.T=function(){G7(this);I7(this);H7(this);g.ys(this.I);this.I=window.NaN;g.ys(this.K);this.K=window.NaN;this.o=null;g.$t(this.V);this.V.length=0;this.g.dispose();D7.xa.T.call(this);this.A=this.F=this.l=this.Na=this.g=null};
g.h.iA=function(){this.C(2)};
g.h.ZF=function(){E7("Channel opened");this.R&&(this.R=!1,H7(this),this.P=g.ws((0,g.A)(function(){E7("Timing out waiting for a screen.");this.C(1)},this),15E3));
Wja(gka(this.g),this.W)};
g.h.WF=function(){E7("Channel closed");(0,window.isNaN)(this.B)?T4(!0):T4();this.dispose()};
g.h.XF=function(a){T4();(0,window.isNaN)(this.G())?(E7("Channel error: "+a+" without reconnection"),this.dispose()):(this.R=!0,E7("Channel error: "+a+" with reconnection in "+this.G()+" ms"),F7(this,2))};
g.h.YF=function(a){a.params?E7("Received: action="+a.action+", params="+g.Kg(a.params)):E7("Received: action="+a.action+" {}");switch(a.action){case "loungeStatus":a=g.cr(a.params.devices);this.l=(0,g.G)(a,function(a){return new B4(a)});
a=!!g.Oa(this.l,function(a){return"LOUNGE_SCREEN"==a.type});
L7(this,a);break;case "loungeScreenDisconnected":g.Ya(this.l,function(a){return"LOUNGE_SCREEN"==a.type});
L7(this,!1);break;case "remoteConnected":var b=new B4(g.cr(a.params.device));g.Oa(this.l,function(a){return b?a.id==b.id:!1})||g.Va(this.l,b);
break;case "remoteDisconnected":b=new B4(g.cr(a.params.device));g.Ya(this.l,function(a){return b?a.id==b.id:!1});
break;case "gracefulDisconnect":break;case "playlistModified":M7(this,a);break;case "nowPlaying":Bka(this,a);break;case "onStateChange":N7(this,a);break;case "onAdStateChange":Cka(this,a);break;case "onVolumeChanged":Dka(this,a);break;case "onSubtitlesTrackChanged":Aka(this,a);break;case "nowAutoplaying":Eka(this,a);break;case "autoplayDismissed":this.O("autoplayDismissed");break;case "autoplayUpNext":this.F=a.params.videoId||null;this.O("autoplayUpNext",this.F);break;case "onAutoplayModeChanged":this.A=
a.params.autoplayMode;this.O("autoplayModeChange",this.A);"DISABLED"==this.A&&this.O("autoplayDismissed");break;case "onHasPreviousNextChanged":Fka(this,a);break;case "requestAssistedSignIn":this.O("assistedSignInRequested",a.params.authCode);break;default:E7("Unrecognized action: "+a.action)}};
g.h.OJ=function(){if(this.o){var a=this.o;this.o=null;this.Na.videoId!=a&&J7(this,"getNowPlaying")}};
D7.prototype.subscribe=D7.prototype.subscribe;D7.prototype.unsubscribeByKey=D7.prototype.Fc;D7.prototype.la=function(){var a=3;this.ga()||(a=0,(0,window.isNaN)(this.G())?d6(this.g)&&(0,window.isNaN)(this.B)&&(a=1):a=2);return a};
D7.prototype.getProxyState=D7.prototype.la;D7.prototype.C=function(a){E7("Disconnecting with "+a);G7(this);this.O("beforeDisconnect",a);1==a&&T4();c6(this.g,a);this.dispose()};
D7.prototype.disconnect=D7.prototype.C;D7.prototype.ha=function(){var a=this.Na;this.o&&(a=this.Na.clone(),q7(a,this.o,a.index));return r7(a)};
D7.prototype.getPlayerContextData=D7.prototype.ha;
D7.prototype.pa=function(a){var b=new l7(a);b.videoId&&b.videoId!=this.Na.videoId&&(this.o=b.videoId,g.ys(this.I),this.I=g.ws((0,g.A)(this.OJ,this),5E3));var c=[];this.Na.listId==b.listId&&this.Na.videoId==b.videoId&&this.Na.index==b.index||c.push("remoteQueueChange");this.Na.g==b.g&&this.Na.volume==b.volume&&this.Na.muted==b.muted&&p7(this.Na)==p7(b)&&g.Kg(this.Na.l)==g.Kg(b.l)||c.push("remotePlayerChange");this.Na.reset(a);(0,g.D)(c,function(a){this.O(a)},this)};
D7.prototype.setPlayerContextData=D7.prototype.pa;D7.prototype.X=function(){var a=this.g.C.id,b=g.Oa(this.l,function(b){return"REMOTE_CONTROL"==b.type&&b.id!=a});
return b?b.id:""};
D7.prototype.getOtherConnectedRemoteId=D7.prototype.X;D7.prototype.G=function(){var a=this.g;return a.l.isActive()?a.l.l-(0,g.E)():window.NaN};
D7.prototype.getReconnectTimeout=D7.prototype.G;D7.prototype.ba=function(){return this.A||"UNSUPPORTED"};
D7.prototype.getAutoplayMode=D7.prototype.ba;D7.prototype.ea=function(){return this.F||""};
D7.prototype.getAutoplayVideoId=D7.prototype.ea;D7.prototype.za=function(){if(!(0,window.isNaN)(this.G())){var a=this.g.l;g.Qq(a.g);a.start()}};
D7.prototype.reconnect=D7.prototype.za;D7.prototype.na=function(a,b){J7(this,a,b);K7(this)};
D7.prototype.sendMessage=D7.prototype.na;g.C(O7,p6);g.h=O7.prototype;g.h.td=function(a){return this.zc.$_gs(a)};
g.h.contains=function(a){return!!this.zc.$_c(a)};
g.h.get=function(a){return this.zc.$_g(a)};
g.h.start=function(){this.zc.$_st()};
g.h.add=function(a,b,c){this.zc.$_a(a,b,c)};
g.h.remove=function(a,b,c){this.zc.$_r(a,b,c)};
g.h.Nl=function(a,b,c,d){this.zc.$_un(a,b,c,d)};
g.h.T=function(){for(var a=0,b=this.l.length;a<b;++a)this.zc.$_ubk(this.l[a]);this.l.length=0;this.zc=null;O7.xa.T.call(this)};
g.h.NK=function(){this.O("screenChange")};
g.h.FH=function(){this.O("onlineScreenChange")};
C6.prototype.$_st=C6.prototype.start;C6.prototype.$_gspc=C6.prototype.OK;C6.prototype.$_gsppc=C6.prototype.Yx;C6.prototype.$_c=C6.prototype.contains;C6.prototype.$_g=C6.prototype.get;C6.prototype.$_a=C6.prototype.add;C6.prototype.$_un=C6.prototype.Nl;C6.prototype.$_r=C6.prototype.remove;C6.prototype.$_gs=C6.prototype.td;C6.prototype.$_gos=C6.prototype.Xx;C6.prototype.$_s=C6.prototype.subscribe;C6.prototype.$_ubk=C6.prototype.Fc;var P7=null,Q7=null,f8=null,U7=[];g.r(i8,g.I);g.h=i8.prototype;
g.h.T=function(){g.I.prototype.T.call(this);this.A.stop();this.B.stop();this.L.stop();this.R();this.g.unsubscribe("proxyStateChange",this.Hv,this);this.g.unsubscribe("remotePlayerChange",this.dj,this);this.g.unsubscribe("remoteQueueChange",this.nl,this);this.g.unsubscribe("autoplayUpNext",this.ev,this);this.g.unsubscribe("previousNextChange",this.Ev,this);this.g.unsubscribe("nowAutoplaying",this.Av,this);this.g.unsubscribe("autoplayDismissed",this.dv,this);this.g=this.G=null};
g.h.fu=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];if(2!=this.g.g)if(m8(this)){if(!v7(this.g).isAdPlaying()||"control_seek"!=a)switch(a){case "control_toggle_play_pause":1==v7(this.g).g?this.g.pause():this.g.play();break;case "control_play":this.g.play();break;case "control_pause":this.g.pause();break;case "control_seek":this.K.oh(c[0],c[1]);break;case "control_subtitles_set_track":n8(this,c[0]);break;case "control_set_audio_track":c=c[0],m8(this)&&this.g.Tp(this.l.Z(1).videoId,
c)}}else switch(a){case "control_toggle_play_pause":case "control_play":case "control_pause":c=this.l.ya();o8(this,0==c?void 0:c);break;case "control_seek":o8(this,c[0]);break;case "control_subtitles_set_track":n8(this,c[0]);break;case "control_set_audio_track":c=c[0],m8(this)&&this.g.Tp(this.l.Z(1).videoId,c)}};
g.h.TF=function(a){this.L.dA(a)};
g.h.uK=function(a){this.fu("control_subtitles_set_track",g.fc(a)?null:a)};
g.h.ax=function(){var a=this.l.Ob("captions","track");g.fc(a)||n8(this,a)};
g.h.yv=function(a){if(m8(this)){this.g.unsubscribe("remotePlayerChange",this.dj,this);var b=Math.round(a.volume);a=!!a.muted;var c=v7(this.g);if(b!=c.volume||a!=c.muted)this.g.setVolume(b,a),this.P.start();this.g.subscribe("remotePlayerChange",this.dj,this)}};
g.h.ZG=function(){g.fc(this.C)||p8(this,this.C);this.F=!1};
g.h.Hv=function(a,b){this.B.stop();2==b&&this.Yw()};
g.h.dj=function(){if(m8(this)){this.A.stop();var a=v7(this.g);switch(a.g){case 1081:case 1:k8(this,new g.aE(8));this.Xw();break;case 1085:case 3:k8(this,new g.aE(9));break;case 1083:case 0:k8(this,new g.aE(2));this.K.stop();j8(this,this.l.Z().lengthSeconds);break;case 1084:k8(this,new g.aE(4));break;case 2:k8(this,new g.aE(4));j8(this,p7(a));break;case -1:k8(this,new g.aE(64));break;case -1E3:a={errorCode:"mdx.remoteerror",message:g.Q("YTP_MDX_PLAYER_ERROR")},k8(this,new g.aE(128,a))}a=v7(this.g).l;
var b=this.C;(a||b?a&&b&&a.trackName==b.trackName&&a.languageCode==b.languageCode&&a.languageName==b.languageName&&a.format==b.format&&a.kind==b.kind:1)||(this.C=a,p8(this,a));a=v7(this.g);-1==a.volume||Math.round(this.l.Nb())==a.volume&&this.l.isMuted()==a.muted||this.P.isActive()||this.Kx()}else l8(this)};
g.h.Ev=function(){this.l.O("mdxpreviousnextchange")};
g.h.nl=function(){m8(this)||l8(this)};
g.h.Cz=function(){this.g.xr()};
g.h.ev=function(a){a&&(a=g.Ns("/watch_queue_ajax",{method:"GET",uc:{action_get_watch_queue_item:1,video_id:a},ob:(0,g.A)(this.ZI,this)}))&&(this.R=(0,g.A)(a.abort,a))};
g.h.ZI=function(a,b){var c=new g.$C({videoId:b.videoId,title:b.title,author:b.author,murlmq_webp:b.url});this.suggestion=c;this.l.O("mdxautoplayupnext",c)};
g.h.Av=function(a){(0,window.isNaN)(a)||this.l.O("mdxnowautoplaying",a)};
g.h.dv=function(){this.l.O("mdxautoplaycanceled")};
g.h.QD=function(a,b){-1==v7(this.g).g?o8(this,a):b&&this.g.Vx(a)};
g.h.Kx=function(){if(m8(this)){var a=v7(this.g);this.o.Ra(this.V);a.muted?this.l.mute():this.l.Ge();this.l.setVolume(a.volume);this.V=this.o.M(this.l,"onVolumeChange",this.yv)}};
g.h.Xw=function(){this.A.stop();if(!this.g.ga()){var a=v7(this.g);1==a.g&&k8(this,new g.aE(8));j8(this,p7(a));this.A.start()}};
g.h.Yw=function(){this.B.stop();this.A.stop();var a=this.g.A.getReconnectTimeout();2==this.g.g&&!(0,window.isNaN)(a)&&this.B.start()};g.r(s8,g.S);s8.prototype.o=function(a){r8(this,a.state)};g.r(t8,g.tT);t8.prototype.I=function(){var a=this.g.Ob("remote","receivers");a&&1<a.length&&!this.g.Ob("remote","quickCast")?(this.F=g.ob(a,this.A,this),g.uT(this,(0,g.G)(a,this.A)),a=this.g.Ob("remote","currentReceiver"),this.ce(this.A(a)),this.enable(!0)):this.enable(!1)};
t8.prototype.A=function(a){return a.key};
t8.prototype.be=function(a){return"cast-selector-receiver"==a?g.Q("YTP_MDX_CAST_SELECTOR"):this.F[a].name};
t8.prototype.Kc=function(a){g.tT.prototype.Kc.call(this,a);this.g.Wc("remote","currentReceiver",this.F[a]);this.o.rb()};g.r(u8,g.TK);g.h=u8.prototype;g.h.create=function(){Kka(g.qB(g.W(this.g)));this.C.push(g.Du("yt-remote-before-disconnect",this.QF,this));this.C.push(g.Du("yt-remote-connection-change",this.gI,this));this.C.push(g.Du("yt-remote-receiver-availability-change",this.Fv,this));this.C.push(g.Du("yt-remote-auto-connect",this.eI,this));this.C.push(g.Du("yt-remote-receiver-resumed",this.dI,this));this.Fv()};
g.h.load=function(){this.g.lo();g.TK.prototype.load.call(this);this.B=new i8(this,this.g,this.l);var a=(a=h8())?a.currentTime:0;var b=e8()?new u7($7(),void 0):null;0==a&&b&&(a=p7(v7(b)));0!=a&&(this.F=a||0,this.g.O("progresssync",a,void 0));q8(this,this.G,this.G);g.eV(this.g.app,6)};
g.h.unload=function(){this.g.O("mdxautoplaycanceled");this.A=this.o;g.Ze(this.B,this.l);this.l=this.B=null;g.TK.prototype.unload.call(this);g.eV(this.g.app,5)};
g.h.T=function(){g.Eu(this.C);g.TK.prototype.T.call(this)};
g.h.Ti=function(a,b){for(var c=[],d=1;d<arguments.length;++d)c[d-1]=arguments[d];this.loaded&&this.B.fu.apply(this.B,[a].concat(g.qa(c)))};
g.h.aA=function(){return this.loaded?this.B.suggestion:null};
g.h.ue=function(){return this.l?v7(this.l).ue:!1};
g.h.hasNext=function(){return this.l?v7(this.l).hasNext:!1};
g.h.GD=function(){var a=v7(this.l),b=this.g.Z();return{allowSeeking:this.g.Cc(),clipEnd:b.clipEnd,clipStart:b.clipStart,current:this.F,displayedStart:-1,duration:a.C?a.I+n7(a):a.I,ingestionTime:a.C?a.A+n7(a):a.A,isPeggedToLive:1>=(a.C?a.o+n7(a):a.o)-this.F,loaded:a.K,seekableEnd:a.C?a.o+n7(a):a.o,seekableStart:0<a.B?a.B+n7(a):a.B}};
g.h.HD=function(){this.l&&this.l.Tx()};
g.h.ID=function(){this.l&&this.l.Ux()};
g.h.QF=function(a){1==a&&(this.K=this.l?v7(this.l):null)};
g.h.gI=function(){var a=e8()?new u7($7(),void 0):null;if(a){var b=this.A;this.loaded&&this.unload();this.l=a;this.K=null;b.key!=this.o.key&&(this.A=b,this.load())}else g.Ye(this.l),this.l=null,this.loaded&&(this.unload(),(a=this.K)&&a.videoId==this.g.Z().videoId&&this.g.Jt(a.videoId,p7(a)));this.g.O("videodatachange","newdata",this.g.Z(),3)};
g.h.Fv=function(){this.I=[this.o].concat(Lka());var a=a8()||this.o;v8(this,a);this.g.ka("onMdxReceiversChange")};
g.h.eI=function(){var a=a8();v8(this,a)};
g.h.dI=function(){this.A=a8()};
g.h.FD=function(a,b){switch(a){case "casting":return this.loaded;case "receivers":return this.I;case "currentReceiver":return b&&("cast-selector-receiver"==b.key?j7():v8(this,b)),this.loaded?this.A:this.o;case "quickCast":return 2==this.I.length&&"cast-selector-receiver"==this.I[1].key?(b&&j7(),!0):!1}};
g.h.JD=function(){A7(this.l,"sendDebugCommand",{debugCommand:"stats4nerds "})};
g.h.gc=function(){return!1};g.KQ.remote=u8;})(_yt_player);
