import os
import sys
os.system('gcc genData.c -o gendata.out')
os.system('g++ -std=c++17 ' + sys.argv[1])
print("Sorted")
print('10k')
os.system('./gendata.out 10000 0 data-sorted.txt')
os.system('./a.out data-sorted.txt')
print('20k')
os.system('./gendata.out 20000 0 data-sorted.txt')
os.system('./a.out data-sorted.txt')
print('50k')
os.system('./gendata.out 50000 0 data-sorted.txt')
os.system('./a.out data-sorted.txt')
print('100k')
os.system('./gendata.out 100000 0 data-sorted.txt')
os.system('./a.out data-sorted.txt')
print()
print("Random")
print('10k')
os.system('./gendata.out 10000 1 data-random.txt')
os.system('./a.out data-random.txt')
print('20k')
os.system('./gendata.out 20000 1 data-random.txt')
os.system('./a.out data-random.txt')
print('50k')
os.system('./gendata.out 50000 1 data-random.txt')
os.system('./a.out data-random.txt')
print('100k')
os.system('./gendata.out 100000 1 data-random.txt')
os.system('./a.out data-random.txt')

print()
print("Reverse")
print('10k')
os.system('./gendata.out 10000 2 data-reverse.txt')
os.system('./a.out data-reverse.txt')
print('20k')
os.system('./gendata.out 20000 2 data-reverse.txt')
os.system('./a.out data-reverse.txt')
print('50k')
os.system('./gendata.out 50000 2 data-reverse.txt')
os.system('./a.out data-reverse.txt')
print('100k')
os.system('./gendata.out 100000 2 data-reverse.txt')
os.system('./a.out data-reverse.txt')




